### ISSUE TITLE
Authelia 4: too many open files/sockets with traefik 2.1.3

### ISSUE THREAD

**Issue by ZyanKLee** [authelia/authelia#596] opened 2020-01-29 14:21 UTC
Hello Authelia Develops,

I've got an issue with open files or sockets when running authelia with traefik 2.1.3
Over at the traefik project I already opened an issue and would like to ask you to take a look at this as well. Perhaps you can add some more insight into it?

https://github.com/containous/traefik/issues/6252

Thanks a lot!

**Comment by james-d-elliott** [comment] 2020-01-29 19:43
Thanks for posting your issue. Even if it turns out to be an issue at Traefik's end it'd be nice for our users to be aware of it. Have you checked the Authelia logs to see if there is anything obvious? I have a feeling this is a Traefik issue, it should close the connections when it is done. But we will make sure.

Does auth work as you would expect until this problem comes up?

**Comment by ZyanKLee** [comment] 2020-01-29 19:57
Authentication works fine. My configuration worked for two weeks, but every
12-16 hours one of those two services needs to be restarted to flush the
sockets.

**Comment by james-d-elliott** [comment] 2020-01-29 20:01
Your issue is actually a duplicate of https://github.com/containous/traefik/issues/6229. Both users were using Traefik 2.0, probably Authelia v4 too. Would you post your configuration?

**Comment by james-d-elliott** [comment] 2020-01-29 20:04
I'm marking this as a bug for now even though it could be at Traefik's end. Do you think you can try a v3 to test it @ZyanKLee @GHDiscard ?

**Comment by ZyanKLee** [comment] 2020-01-30 09:34
hmm, it was tagged as latest (will change that to the exact version now).
the image is output by docker as such:
```
authelia/authelia                            latest              aacea09e125f        8 days ago          33.2MB
```

**Comment by james-d-elliott** [comment] 2020-01-30 20:26
@ZyanKLee I'm really interested in replicating your setup as closely as possible. Are you using docker compose? Could you provide a compose if so? Or are you just doing create/run commands?

**Comment by ZyanKLee** [comment] 2020-01-31 06:27
Hey James, yes i use docker-compose on an aws ec2 instance. There is an application elb in front of the whole system.

**Comment by ZyanKLee** [comment] 2020-01-31 06:28
A sample config is in the ticket I created at traefik

**Comment by ZyanKLee** [comment] 2020-01-31 06:43
One thing that might be related, but not sure it can be: SSL termination is on the elb; so the elb, traefik and authelia and all services communicate via http but the service is called via https in the browser

**Comment by ZyanKLee** [comment] 2020-01-31 08:26
for convenience I'll copy the contents of the traefik issue in here:


> 
> ### What did you do?
> 
> Set up a monitoring system consisting of traefik with some service behind it, i.e. grafana, kibana, prometheus, authelia, alerta and others.
> 
> traefik uses authelia as a forwardAuthentication service for those tools that do not provide an authentication interfaces on their own (i.e. kibana).
> 
> ### What did you expect to see?
> 
> I expected the amount of open files / sockets rising and declining with the rate of usage of the system.
> 
> ### What did you see instead?
> 
> After several hours the max open files limit was reached and connections from traefik to its services aren't successful anymore - as in: the browser page stays blank and there is no error message shown. 
> 
> I recognized within grafana (after a restart of traefik, obviously) some odd measurements.
> 
> On this graph you can see the constant growth of open sockets on the host system:
> ![Bildschirmfoto 2020-01-28 um 15 37 05](https://user-images.githubusercontent.com/1178490/73274345-b9475f00-41e5-11ea-83d9-02dde3150bde.png)
> 
> This second graph illustrates the growth rate (`non_negative_difference`) of the two most significant timeserieses:
> ![Bildschirmfoto 2020-01-28 um 15 41 02](https://user-images.githubusercontent.com/1178490/73274482-ea279400-41e5-11ea-8ff2-466e02f3c7cb.png)
> 
> That nicely shows how the amount of requests relates to the number of open file descriptors. The other three timeserieses that are excluded in this view show similar behaviour but do have some more spikes that are clearly not related to the issue (or most probably closed again afterwards).
> 
> ### Output of `traefik version`: (_What version of Traefik are you using?_)
> 
> docker-compose exec reverseproxy traefik version
> Version:      2.1.3
> Codename:     cantal
> Go version:   go1.13.6
> Built:        2020-01-21T17:30:29Z
> OS/Arch:      linux/amd64
> 
> ### What is your environment & configuration (arguments, toml, provider, platform, ...)?
> 
> ```toml
> [providers.docker]
>   exposedByDefault = false
>   defaultRule = ''
> 
> [entryPoints]
>   [entryPoints.http]
>     address = ":80"
>       [entryPoints.http.proxyProtocol]
>         insecure = true
>       [entryPoints.http.forwardedHeaders]
>         insecure = true
> 
> [api]
>   dashboard = true
>   insecure = true
> 
> [metrics]
>   [metrics.prometheus]
> 
> [ping]
>   entrypoint = "http"
> 
> [log]
>   level = "ERROR"
> ```
> 
> part of the docker-compose.yaml as an example:
> ```yaml
> ---
> version: "3.4"
> 
> services:
> 
>   reverseproxy:
>     container_name: reverseproxy
>     image: traefik:2.1.3
>     restart: always
>     labels:
>     - "namespace=proxy"
>     - "traefik.enable=true"
>     - "traefik.http.routers.reverseproxy.rule=Host(`traefik.${BASEDOMAIN}`)"
>     - "traefik.http.routers.reverseproxy.service=api@internal"
>     - "traefik.http.routers.reverseproxy.middlewares=reverseproxy-auth@docker"
>     - 'traefik.http.middlewares.reverseproxy-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${BASEDOMAIN}'
>     - "traefik.http.middlewares.reverseproxy-auth.forwardauth.trustForwardHeader=true"
>     - "traefik.http.middlewares.reverseproxy-auth.forwardauth.tls.insecureSkipVerify=true"
>     ports:
>     - 80:80
>     volumes:
>     - /var/run/docker.sock:/var/run/docker.sock
>     - ./traefik/config/:/etc/traefik/
>     ulimits:
>       nproc: 65535
>       nofile:
>         soft: 1000000
>         hard: 1000000
> 
>   authelia:
>     container_name: authelia
>     image: authelia/authelia
>     restart: always
>     ports:
>     - 9091
>     volumes:
>     - ./authelia/config/configuration.yml:/etc/authelia/configuration.yml
>     - authelia-data:/var/lib/authelia
>     environment:
>       TZ: Europe/Berlin
>     labels:
>     - "namespace=proxy"
>     - "traefik.enable=true"
>     - "traefik.http.routers.authelia.rule=Host(`auth.${BASEDOMAIN}`)"
>     - "traefik.http.routers.authelia.middlewares=authelia-headers@docker,authelia-regex@docker"
>     - "traefik.http.middlewares.authelia-headers.headers.customrequestheaders.X-Forwarded-Proto:https"
>     - "traefik.http.middlewares.authelia-regex.redirectregex.regex=(.*rd=)(https?://?)([^/].*)"
>     - "traefik.http.middlewares.authelia-regex.redirectregex.replacement=$${1}https://$${3}"
>     ulimits:
>       nproc: 65535
>       nofile:
>         soft: 1000000
>         hard: 1000000
> 
>   kibana:
>     container_name: kibana
>     build: kibana
>     image: local/kibana:latest
>     restart: always
>     ports:
>     - 5601
>     environment:
>       ES_HOSTS:
>     healthcheck:
>       test: ["CMD", "curl", "-f", "http://localhost:5601/api/status"]
>       interval: 30s
>       timeout: 10s
>       retries: 3
>     volumes:
>     - ./kibana/config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
>     - kibana-data:/usr/share/kibana/data
>     labels:
>     - "traefik.enable=true"
>     - "traefik.http.routers.kibana.rule=Host(`kibana.${BASEDOMAIN}`)"
>     - "traefik.http.routers.kibana.middlewares=kibana-auth@docker"
>     - "traefik.http.middlewares.kibana-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${BASEDOMAIN}"
>     - "traefik.http.middlewares.kibana-auth.forwardauth.trustForwardHeader=true"
>     - "traefik.http.middlewares.kibana-auth.forwardauth.tls.insecureSkipVerify=true"
>     - "namespace=monitoring"
> ```
> 
> ### If applicable, please paste the log output in DEBUG level (`--log.level=DEBUG` switch)
> 
> ```
> found no errors in there - if absolutely needed, I can provide a privacy- and security-enhanced version of it.
> ```
>

**Comment by james-d-elliott** [comment] 2020-01-31 20:36
I must be blind, I didn't see the compose on the other post. Thanks!

**Comment by james-d-elliott** [comment] 2020-01-31 21:49
So I'm not 100% sure this is your issue, but this certainly will cause problems:

`    - 'traefik.http.middlewares.reverseproxy-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://auth.${BASEDOMAIN}'`

Should be:

`    - 'traefik.http.middlewares.reverseproxy-auth.forwardauth.address=http://authelia:9091/api/verify?rd=https://traefik.${BASEDOMAIN}'`

**Comment by ZyanKLee** [comment] 2020-02-01 11:40
somewhat - its based on the amazon opendistro elasticsearch kibana image but removes the authentication plugin: https://hub.docker.com/r/amazon/opendistro-for-elasticsearch-kibana

**Comment by ZyanKLee** [comment] 2020-02-01 12:28
Maybe I can help you with the traefik issues?

**Comment by james-d-elliott** [comment] 2020-02-01 23:42
@ZyanKLee it was just a typo. I figured it out, I now have a compose showing the issue and now just need to figure out where the issue exists; which I have a methodical plan for.

**Comment by james-d-elliott** [comment] 2020-02-02 04:04
So I have managed to narrow this down to the tls.insecureSkipVerify=true setting. This I believe can just be turned off without issue. As for what's causing it, I'm pretty sure this is a bug with traefik, however it could be argued it's a bad configuration.

What it looks like is as soon as you turn that on it also turns on TLS. This in my opinion should generate a warning, or show a status issue with the forward auth middleware.

**Comment by james-d-elliott** [comment] 2020-02-02 05:40
@ZyanKLee to quickly figure out if my fix resolves your issue, disable tls.insecureSkipVerify in Traefik. Then run the following commands on the docker host, and generate some activity:

docker inspect -f '{{.State.Pid}}' <container name of authelia>
watch nsenter -t <pid> -n netstat

**Comment by james-d-elliott** [comment] 2020-02-02 23:00
Based on the following factors I think I'm going to close this issue:
* A configuration change will fix the issue (don't use tls.insecureSkipVerify=true)
* Upstream has a working fix for the theoretical bug
* This comment seems to indicate resolution for @ZyanKLee - https://github.com/containous/traefik/issues/6229#issuecomment-581184966

Feel free to comment/reopen if your issue is not resolved.

**Closed by james-d-elliott** 2020-02-02 23:00 UTC
Labels: P1, bug-possible, integration-issue

**Comment by ZyanKLee** [comment] 2020-02-03 10:41
yes, thank you very much for the help

**Comment by james-d-elliott** [comment] 2020-02-03 20:40
Note: this bug has been fixed in a merge upstream: https://github.com/containous/traefik/pull/6267
