### ISSUE TITLE
Maximum header size restricted to 4096 bytes

### ISSUE THREAD

**Issue by kusold** [authelia/authelia#518] opened 2019-12-22 16:56 UTC
I have an application that uses a large header size, but fasthttp limits the size of the header by default.

Authelia should be able to pass through configurations to fasthttp:
https://godoc.org/github.com/valyala/fasthttp#Server

https://github.com/authelia/authelia/blob/3fb84fabc2cb4501772a5a8b6bba9d81153f83c2/internal/server/server.go#L106-L107

Alternatively: Is there a reason to use fasthttp? What was `net/http` not able to provide?

I downgraded to v3, and validated that my setup works. This is a regression in v4.

**Comment by kusold** [comment] 2019-12-22 17:20
Alternatively: Is there a reason to use fasthttp? What was `net/http` not able to provide?

**Comment by clems4ever** [comment] 2019-12-27 16:22
Hello @kusold , thank you for reporting this issue. I'm wondering what is that header holding more than 4096 bytes sent to Authelia? Is it supposed to be delivered to Authelia somehow?
If it's X-Forwarded-For, X-Forwarded-Proto, X-Forwarded-Host, X-Forwarded-URI or X-Real-IP, I guess it's a regression. Otherwise it's a misconfiguration, this header should simply be stripped in the reverse proxy configuration in order to not transmit headers that are not supposed to reach Authelia.

Regarding your question about fasthttp, I had to make a choice at some point and I wanted Authelia to handle a high throughput and reduce the price of the hop to the minimum. But I'm open to change my mind if I see any valid reason to rollback.

**Comment by kusold** [comment] 2019-12-28 02:56
The header is a large JWT token that needs to get passed to a backend service (kibana in this particular case) for authorization purposes. I currently have the service setup with a bypass rule in Authelia, but it still is subject to the header size limit.

**Comment by clems4ever** [comment] 2019-12-28 08:12
Ok so right now this header should simply be stripped because it is not supposed to be sent to Authelia. However, it could definitely be a problem when OAuth2 is implemented. I will keep this use case in mind for the future. Please strip the header and let us know if everything works for you in v4 or if you need more assistance.

**Comment by nightah** [comment] 2020-01-10 06:06
@kusold have you had any luck with this?

**Comment by kusold** [comment] 2020-01-10 13:04
@nightah I downgraded to v3, because it doesn’t have a header size limit. The main bottleneck is that because Traefik sends every request through Authelia, there isn’t a way to strip the header for Authelia but preserve it for the receiving service.

**Comment by james-d-elliott** [comment] 2020-04-06 05:30
@kusold if you're still interested in solving this, mind testing it for me? I think I have a fix sorted out.

If you're using docker, the image will be tagged `authelia/authelia:misc-max-header-size` if not you can grab an artifact from here: https://buildkite.com/authelia/authelia/builds/1241#1a6eddeb-d013-437d-962d-a9efdc1c0de6

You will need to add read_buffer_size: <int> to your configuration.

**Comment by nightah** [comment] 2020-04-09 04:46
ping @kusold would be great to get your feedback on this so that we can close this issue off.

**Comment by nightah** [comment] 2020-04-15 13:01
@kusold, I'm closing this off in the interim.

We will leave the `feature-read-buffer-size` container there until either you have the opportunity to test or we can simulate your specific use case.

Feel free to ping either of us when/if you get a chance and we can re-open this issue and look to hopefully get that change merged in.

**Closed by nightah** 2020-04-15 13:01 UTC
Labels: Integration Issue, P3

**Comment by james-d-elliott** [comment] 2020-10-17 01:12
@kusold this may be able to be solved by a configuration change with Traefik in the next release. See https://github.com/traefik/traefik/issues/6493

**Comment by Mrs-Feathers** [comment] 2023-07-26 05:40
i'm having the same issue, but for nginx

**Comment by james-d-elliott** [comment] 2023-07-26 06:18
Configure the buffers: https://www.authelia.com/configuration/miscellaneous/server/

**Comment by Mrs-Feathers** [comment] 2023-08-05 00:09
sadly, that documentation was unhelpful, the page you linked to basically just said "you should change them" and the link for the actual page on buffers was confusing. i couldn't solve this issue so, appologies but i've moved on to Authentik which i was able to set up without issue
