### ISSUE TITLE
help needed: protecting homeassistant mobile with authelia

### ISSUE THREAD

**Issue by repomanz** [authelia/authelia#1842] opened 2021-03-19 17:10 UTC
Hello,

I am using nginx proxy manager and authelia.  I would like to protect my home assistant domain with authelia.  I am using this endpoint protection code in nginx proxy manager advanced settings:

https://github.com/ibracorp/authelia/blob/master/Protected%20Endpoint.conf

This works in web-browsers:

- brower login to has.mydomain.com
- redirected for authentication at auth.mydomain.com
- enter credentials, if successful redirects back to has.mydomain.com

However in the home assistant companion app (android) what occurs is:
- open mobile app
- mobile app launches browser
- brower login to has.mydomain.com
- redirected for authentication at auth.mydomain.com
- enter credentials, if successful redirects back to has.mydomain.com
- home assistant companion app doesn't authenticate

https://github.com/home-assistant/android/issues/1438#issuecomment-802956402
maybe related to this: 
` return if (redirectUrl.startsWith(AUTH_CALLBACK) && !code.isNullOrBlank()) { `

I'm a bit out of my element here but hoping for some direction about how to make this work.

**Comment by james-d-elliott** [comment] 2021-03-19 22:18
Keep #1798 in mind, but I'll see if we can help you. I think there should be a way to accommodate you most likely. I'm getting some additional information from that upstream issue that should help us figure it out.

**Comment by repomanz** [comment] 2021-03-22 01:49
Hi James - thanks for the assist. Much appreciated!

**Comment by james-d-elliott** [comment] 2021-04-07 21:58
@repomanz  it looks like you'll need to implement the following rule:

```yaml
- domain: ha.example.com
  policy: bypass
  resources:
  - "^/api(/.*)?$"
```

**Comment by james-d-elliott** [comment] 2021-04-17 10:46
@repomanz did this solve it for you? Or still an issue?

**Comment by repomanz** [comment] 2021-04-21 19:13
sorry for delay response; I won't be able to test this for a few weeks.  I'll close the ticket for now, if i find issue I'll comment on it.

**Comment by quorn23** [comment] 2021-05-27 01:40
Hi @james-d-elliott 
sorry for posting in this closed issue, as there wasn't any feedback yet, i tried implement the rule.

https://pastebin.com/409G15in

Is this the proper syntax for it? (obvs changed my domain to domain.com)
I restarted Authelia with it and i can't see any difference, it still throws me into the web browser and is either getting stuck, or just loading the dashboard in the browser.

**Comment by james-d-elliott** [comment] 2021-05-27 02:30
> 
> 
> Hi @james-d-elliott
> sorry for posting in this closed issue, as there wasn't any feedback yet, i tried implement the rule.
> 
> https://pastebin.com/409G15in
> 
> Is this the proper syntax for it? (obvs changed my domain to domain.com)
> I restarted Authelia with it and i can't see any difference, it still throws me into the web browser and is either getting stuck, or just loading the dashboard in the browser.

Hey! No worries at all I can reopen it. That's what I *expected* would work but that was based on HomeAssistants documentation. Can you provide some Authelia logs when you attempt to use the app so we can try to narrow this down? Basically there should be logs indicating which URL's are being denied.

**Comment by quorn23** [comment] 2021-05-30 20:16
[https://pastebin.com/J7DPCfQM](https://pastebin.com/J7DPCfQM)

Here you go James.
Notes: 
Changed domain to DOMAIN.COM
Ip to 000.000.000.000
Username to USER
I removed a bunch of lines of hs loading js files, as it was all the same, just different names to not have an endless log.

Steps:
Opening Homeassistant App
It opens a browser with Authelia.
Authenticated myself and added my 2FA code
It loads the HS page (in the browser) with this error: [https://imgur.com/a/zkkV0Kx](https://imgur.com/a/zkkV0Kx)
Once i click "retry" i get forwarded to my dashboard in the browser

**Comment by james-d-elliott** [comment] 2021-05-30 20:20
Try changing it to the following:

```yaml
- domain: ha.example.com
  policy: bypass
  resources:
  - "^/api(/.*)?$"
  - "^/?external_auth=\d+$"

**Comment by quorn23** [comment] 2021-05-30 20:25
Throws me a 500 internal server error. But not just for the ha domain, for all of authelia.

```today at 10:22:17 PM time="2021-05-30T20:22:17Z" level=error msg="Error malformed yaml: line 49: found unknown escape character"```

Line 49 is the last line

**Comment by quorn23** [comment] 2021-05-30 20:43
Added the \\ instead of \ sadly same behavior, getting the "unable connect" error and then it forwards me to the dashboard in the browser, not seeing any difference in the logs

**Comment by james-d-elliott** [comment] 2021-05-30 21:57
It may have to be `\\\`, or try this:

```yaml
- domain: ha.example.com
  policy: bypass
  resources:
  - "^/api(/.*)?$"
  - "^/?external_auth=$"

**Comment by quorn23** [comment] 2021-05-30 23:53
The double backslash works, triple not.
Trued the new line
Same behavior
 [https://pastebin.com/TQ7CJbZf](https://pastebin.com/TQ7CJbZf)

Note: Last line is from closing app+browser and reopening it again, getting forwarded to the browser.

**Comment by pmorange** [comment] 2021-10-14 13:26
Hi, with these rules I was able to make it work in the app while still protecting the web version :

```
- domain: "ha.morange.ovh"
  policy: bypass
  resources:
    - "^/api.*"
    - "^/auth/token/.*"
    - "^/.external_auth=."
    - "^/service_worker.js"
    - "^/static/.*"
- domain: # Proxies needing 2 factor below
    - "ha.morange.ovh"
  policy: two_factor
```

**Comment by james-d-elliott** [comment] 2021-10-15 03:46
Thanks for posting @pmorange - does this still require standard auth via HA from the app?

**Comment by pmorange** [comment] 2021-10-15 06:30
> Thanks for posting @pmorange - does this still require standard auth via HA from the app?

Hi,
It does not require it, both are independent, so you can choose what to do. Currently I have both Authelia auth and also login in each app behind Authelia. Some with just a user and pass, others with double authentification, which would sum to 4FA in that case hahaha. 
Surely I'll grow tired of so much security if apps ask me too much for my credentials in the future, but for now I have this extra security for everything connected to the web, which can never be enough... I'm counting on apps' sessions lasting long enough for them not to log me out too often. HA for instance can keep you logged in for a long time.

Note : I also commented the same rules in this post where they talked about the same thing : https://community.home-assistant.io/t/anyone-have-authelia-working-with-ha-to-handle-authentication/321233/18?u=thejuice

**Comment by nightah** [comment] 2021-11-11 03:27
@repomanz I'm closing this issue as I believe a workaround/fix has been proposed here.

If the solutions do not address your issue please let us know and we can reopen the issue.

**Closed by nightah** 2021-11-11 03:27 UTC

**Comment by pmorange** [comment] 2021-11-22 08:36
Hi,
Please reopen the issue.

After a while (several days/weeks), the app ceases to open correctly.
It seems authentication is lost with a need to re-authenticate because the following appears in the Authelia logs :
```
time="2021-11-22T09:29:44+01:00" level=info msg="Access to https://ha.morange.ovh/frontend_latest/core.2fe29b5a.js (method unknown) is not authorized to user <anonymous>, responding with status code 401" method=GET path=/api/verify remote_ip=xx.xx.xx.xx.xx
```
Note the "user <anonymous>" part.

The weird thing is if I click in the app on "refresh external URL" (I'm not sure about the exact phrase), a browser opens and correctly logs in HA, so the authentication problem only is in the app, not the whole phone. Probably some cookie left over.

The problem is that when all of this occurs, I don't see a way of authentication again, as the browser does not ask for Authelia login. If the only way is deleting all HA data and cache each time, I don't see this as a workaround because it is too cumbersome to do this frequently.

**Comment by nightah** [comment] 2021-11-23 01:04
Sounds like the duration of your session has expired hence expiring said cookie.
I don't personally use HA or the application so probably would have to set it up to try and replicate the issue.

Can you confirm if the rough time aligns with your session expiration (including the duration of the remember_me option if you set it during login).

**Comment by pmorange** [comment] 2021-11-23 11:23
> Sounds like the duration of your session has expired hence expiring said cookie. I don't personally use HA or the application so probably would have to set it up to try and replicate the issue.
> 
> Can you confirm if the rough time aligns with your session expiration (including the duration of the remember_me option if you set it during login).

Hi,
It could be a session expiration thing --I thought about that--, but in the app without Authelia I never had to login again after the first time, and I neither need to in the web frontend... So it seems my sessions never expire.
I always check "Remember me", or at least intend to, but I can forget of course.

**Comment by nightah** [comment] 2021-11-24 02:08
I've just looked at the extract you provided again and the path it's serving `frontend_latest/core.2fe29b5a.js` isn't part of your bypass rule.

It looks like that could be a static asset - can you confirm?

If you're never logging in to Authelia via the Phone app then it's unlikely for it to be an Authelia issue/session timeout issue it's much more likely to be an asset required by the app that isn't being bypassed.

**Comment by pmorange** [comment] 2021-11-24 09:29
Hi,
Adding frontend_latest to the (already long) list of bypass paths seems to do the trick.
It's weird it happens some time after everything has been working well, but seeing the name of the folder, I have a theory : after an update of HA, on the web and in the app you often see a "a new version of the frontend is available, click to reload". So I guess the app was just checking if a new version was indeed available, but having no access to this path it failed. 

The list is now : 
```
- domain: "ha.domain.com"
      policy: bypass
      resources:
        - "^/api.*"
        - "^/auth/token.*"
        - "^/.external_auth=."
        - "^/service_worker.js"
        - "^/static.*"
        - "^/local.*"
        - "^/hacsfiles.*"
        - "^/frontend_latest.*"
```

Thanks

**Comment by pewter77** [comment] 2022-02-01 03:19
Want to do this, but I want to be sure this is not opening me up. Seems like quite a large amount of attack surface is being exposed here.

**Comment by sami-shakir** [comment] 2022-03-29 19:36
I too wish to get this issue sorted but don't feel comfortable bypassing that many endpoints of my setup to the entire internet.

**Comment by hacker1024** [comment] 2022-09-01 14:27
> I too wish to get this issue sorted but don't feel comfortable bypassing that many endpoints of my setup to the entire internet.

The sensitive API endpoints are still protected with regular HA authentication, right?

**Comment by mikew** [comment] 2024-03-10 23:32
It might be overkill, but I've written a tighter Authelia / Home Assistant Auth Provider at https://github.com/mikew/homelab/blob/public/services/home-automation/data/authelia_auth.py

It does similar to hass-auth-header, but since it's aware of Authelia, uses the API to make sure you've got a valid `authelia_session` cookie, and that no weird impersonation is happening. This is to combat people on your network accessing Home Assistant via `IP:PORT` and setting their own `Remote-User` / `Remote-Name` headers.

It also supports groups so you can map Authelia users to Home Assistant Admins, Users, or Read Only.

**Comment by james-d-elliott** [comment] 2024-03-10 23:40
Please feel free to make a PR with the implementation and docs on using it.

**Comment by mikew** [comment] 2024-03-10 23:56
I'd love to, but it relies on users manually patching Home Assistant code unfortunately. If you're okay with that I can include that in the docs. I might borrow what hass-auth-header is doing, because that monkey-patches Home Assistant.

I'd also like to turn it into a proper HACS addon.

**Comment by AlexZLN** [comment] 2024-05-24 21:52
> I'd love to, but it relies on users manually patching Home Assistant code unfortunately. If you're okay with that I can include that in the docs. I might borrow what hass-auth-header is doing, because that monkey-patches Home Assistant.
> 
> I'd also like to turn it into a proper HACS addon.

could you add a little instruction on how to make it work?

**Comment by Shagon94** [comment] 2024-08-11 18:50
To anyone still stuck, I managed to get it working with nginx-proxy-manager and authelia.

Here's how:

https://github.com/authelia/authelia/issues/1842#issuecomment-977695269 this is key, but in the nginx-proxy-manager config we also need to add

```nginx
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
```

As without it websockets just fail when checking the network tab. I used the following configuration for home-assistant in nginx:

```nginx
include /data/nginx/custom/authelia-location.conf;

location / { 
    include /data/nginx/custom/proxy.conf;
    include /data/nginx/custom/authelia-authrequest.conf;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_pass $forward_scheme://$server:$port;
}
```

Where the `authelia-location.conf`, `proxy.conf` and `authelia-authrequest.conf` are the snippets from the [authelia website](https://www.authelia.com/integration/proxies/nginx/#supporting-configuration-snippets)
