### ISSUE TITLE
Automatic Logout Page - Inactivity/Session Expired

### ISSUE THREAD

**Issue by simonholl** [authelia/authelia#2173] opened 2021-07-12 09:33 UTC
### Description

Display a webpage with a message " You have been automatically logged out" and an option to sign in again. Triggered by session expiry, cookie delete, etc.

### Use Case

I find myself using the webpage of an service I am hosting without knowing my session has expired until I click on a link and the page does not respond. I have to then manually refresh to login again. 
A service such as Grafana allows editing and moving of dashboard elements even though the session has unknowingly expired resulting in futile work.

This feature would prevent accidental interaction with an 'expired' webpage.

**Comment by clems4ever** [comment] 2021-07-12 17:50
Thanks for reporting this issue @simonholl .

What do you mean by "does not respond" in your sentence?
> until I click on a link and the page does not respond

Can you please share the content of the browser console (to see the reported error) and also the content of the network tab when you click on the link?

What proxy do you use? nginx, traefik of HAProxy?
What version of Authelia are you running?

**Comment by simonholl** [comment] 2021-07-14 09:55
Hi, @clems4ever. 

Thank you for your response and assistance. Sorry, I'm afraid that's a poor choice of words on my part. I mean to say "does not respond in a way that I expect". 

Traefik v2.4.9
Authelia v4.29.4

As an example I have used my Grafana service webpage and set the Authelia session expiration to 1 minute for testing.
When I interact with the webpage after the session has expired, it will result one of these scenarios. 

1. I can make changes as if the page was still authenticated (Grafana allows me to add a new panel without any error).
2. Click the Grafana 'Save dashboard' button and receive no feedback at all (No error and no output to browser console).
3. Click the Grafana 'Settings' button and receive an error due to the session having expired ('Unexpected error' popup).

Scenario 1 and 2 are misleading because I have little/no indication that the session has expired. 
Scenario 3 is good because I can tell something is wrong and I can reload the page to re-authenticate.


I don't know if this is a bug per se, I would just like some formal way of telling that the session has expired.
I have attached the console log, screenshot and network tab screenshot. 


[console_log.log](https://github.com/authelia/authelia/files/6815170/console_log.log)

![Console](https://user-images.githubusercontent.com/40823260/125601875-eddfe1b9-0894-4878-be34-efbe47245c77.png)
![Network](https://user-images.githubusercontent.com/40823260/125601888-4408c474-747c-4898-bd5e-87e2a22325c8.png)

**Comment by james-d-elliott** [comment] 2021-07-14 10:05
@simonholl just confirming 1 and 2 behavior. Do the changes appear to stick when you revisit the page? Or do they vanish?

**Comment by simonholl** [comment] 2021-07-14 10:14
They stick until I reload the page and re-authenticate via Authelia subdomain. Then everything works as it should.

**Comment by james-d-elliott** [comment] 2021-07-14 10:57
So once you re-authenticate the changes you made are no longer there?

**Comment by simonholl** [comment] 2021-07-14 11:22
Yes. Any changes I make after the session has expired are lost when I re-authenticate.

**Comment by james-d-elliott** [comment] 2021-07-14 23:45
I think I can confirm this bug, I've made a fix that should resolve it, I'd be interested in you testing it since you have a reproducible test case. Keep in mind this should only be used for testing and you should wait until an official release has it to use it in production.

https://github.com/authelia/authelia/pull/2183

The underlying cause is that the 302 status code is only valid for GET/HEAD requests. Every other request should return a 307 as per the MDN: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302

**Comment by james-d-elliott** [comment] 2021-07-14 23:57
Let me know which/if one of those branches fixes it.

**Comment by james-d-elliott** [comment] 2021-07-15 04:42
Nightah tried this and it did not work for nginx (even with manually adjusting the status code). Suspect the issue is more complicated than this however it's probably part of the issue.

**Comment by simonholl** [comment] 2021-07-15 04:51
> Nightah tried this and it did not work for nginx (even with manually adjusting the status code). Suspect the issue is more complicated than this however it's probably part of the issue.

Hmm, I will have a go with the fix using Traefik when I get home this afternoon and report back.

**Comment by james-d-elliott** [comment] 2021-07-15 23:27
Hey I'm going to merge this change into master anyway but I'm not going to consider it a fix. If you've not had a chance to try it then it'll be available on master in about 20 mins.

**Comment by simonholl** [comment] 2021-07-16 06:00
Sorry for the delay, I only got a chance to test this out now.

I don't see any difference in result with the changes added to master. Not seeing any 303 codes, only 302's as before.
I'm afraid its somewhat over my head. 
Let me know if you are looking for anything specific that I can test or help with.

**Comment by james-d-elliott** [comment] 2021-07-16 10:20
>  Let me know if you are looking for anything specific that I can test or help with.

Will do, it's some form of browser security measure and we need to figure out if we can work around it.

**Comment by james-d-elliott** [comment] 2021-07-17 04:09
I think I've figured out a workaround, however I'll have to spend some time researching cross-origin resource sharing to understand what security complications could occur if we are to implement the fix.

**Comment by simonholl** [comment] 2021-07-17 04:27
> I think I've figured out a workaround, however I'll have to spend some time researching cross-origin resource sharing to understand what security complications could occur if we are to implement the fix.

**Comment by simonholl** [comment] 2021-07-17 04:30
Sorry @james-d-elliott accidentally closed this when trying to respond. Finger trouble.
Are you able to re-open it?

That sounds great. I understand it may take some time as it’s rather complicated. Let me know what I can do if anything.

**Comment by james-d-elliott** [comment] 2021-07-17 05:27
So I've gotten the CORS errors to vanish. So the requests succeed.. however the redirection never occurs in the browser view, so I suspect it may be Grafana's javascript interfering with it since I can see the actual GET request to https://auth.domain.com/?etc.

**Comment by simonholl** [comment] 2021-07-17 06:10
Ah, I see. At least it’s some progress, hopefully it’s possible to create a secure workaround.

I’ll do the same and try replicate with the feat-cors branch on another service thats a SPA.

**Comment by james-d-elliott** [comment] 2021-07-17 10:54
> 
> 
> Ah, I see. At least it’s some progress, hopefully it’s possible to create a secure workaround.
> 
> I’ll do the same and try replicate with the feat-cors branch on another service thats a SPA.

@simonholl can you give the feat-cors branch a try :)

**Comment by simonholl** [comment] 2021-07-17 14:24
Thanks @james-d-elliott and @clems4ever, It's working great! Straight after the session expires it automatically redirects me back to the sign-in screen.

**Comment by james-d-elliott** [comment] 2021-07-17 14:27
Nice, now we just have to take a look at tidying this up and fixing nginx configs. I also have to check if this solves a problem I suspect  is related. I suspect it will.

**Comment by james-d-elliott** [comment] 2021-08-04 00:17
Closed by 911d71204f2f5846c7d677d049b3c8d26b6f0637 and #2189

**Closed by james-d-elliott** 2021-08-04 00:17 UTC
Labels: Bug, Feature Request, Integration Issue, P4
