### ISSUE TITLE
Support for multiple devices (hardware keys, mobiles)

### ISSUE THREAD

**Issue by jeppestaerk** [authelia/authelia#275] opened 2018-09-15 13:18 UTC
Hey,

First, what a great application, thank you so much for the work your guys put in this project, and thanks for sharing.

A request for an enhancement:
Support for multiple u2f keys pr user, as it is right now, when you try to add an new ekstra key, it just overwrite the current stored key.
I cut be so nice to have support for multiple keys, in my case i have one yubikey 4 nano permanent in my home laptop, and then i have a yubikey 4 in my key-change for when i need it ex. at my work computer.

All the best to you guys :)
// Jeppe

**Comment by clems4ever** [comment] 2018-09-27 15:54
Hello @jeppestaerk , I agree on the feature. I'll see if I can find some time to implement it. Thank you for reporting.

**Comment by james-d-elliott** [comment] 2019-12-27 17:26
Regarding this tstranex/u2f (used by v4) seems to support it well (so technical implementation is easy): https://github.com/tstranex/u2f/blob/master/auth.go#L17-L27

However there would likely be many UI/UX and a DB schema change required to support it. The ways Google and GitHub do it is ideal. It allows users to specify a description for each key, allows them to add as many as they want, and as necessary remove them individually. Google also allows change of deceptions but that can also be done on GitHub by readding them. Pretty sure ideally this has two new columns in the schema; a unique id, and description. Alternatively you could make the primary key username and keyHandle probably.

It might also be desirable to add a DATETIME column to the schema of u2f_devices to identify when it was added, as well as more information to the authentication logs - though I think the authentication logs change is unrelated to this enhancement.

**Comment by clems4ever** [comment] 2020-05-21 09:28
I'm updating the title to encompass all type of devices (u2f, mobiles with TOTP, duo mobiles).

**Comment by riosolar** [comment] 2021-06-06 12:40
Does having multiple  TOTP devices is now supported?

**Comment by clems4ever** [comment] 2021-06-06 13:37
Hello @riosolar , no only one device is supported for now. I'm now working on the support of FIDO2 and will likely work on adding more devices to be able to efficiently support mobile phones as well as security keys at the same time. FIDO2 is related to webauthn and there is a ticket for it: #241. Stay tuned.

**Comment by Skyfay** [comment] 2022-05-08 15:26
Is it already possible to register several keys?

**Comment by james-d-elliott** [comment] 2022-05-08 21:25
There is no user flow that allows it but the backend does. This is one of the things I'll be aiming to have done for the next release.

**Comment by Skyfay** [comment] 2022-06-22 12:49
> Is it already possible to register several keys?

Watch here: https://www.authelia.com/roadmap/active/webauthn/

**Comment by hleroy** [comment] 2022-10-23 17:46
@james-d-elliott In a previous message, you mentioned that "_There is no user flow that allows it but the backend does_". I checked the CLI documentation, but I couldn't find a CLI command like `authelia storage user webauthn add`.

Could you please explain how we could manually add a key to the backend to help us wait for for [v4.38.0](https://github.com/authelia/authelia/milestone/17)? Thank you.

**Comment by james-d-elliott** [comment] 2022-10-23 19:03
You can change the key description from `Primary` to anything else using SQL.

**Comment by hleroy** [comment] 2022-10-24 18:32
> You can change the key description from `Primary` to anything else using SQL. This will allow you to register a second key via the web UI with the default description, `Primary`.

Excellent, worked perfectly. I'm so glad I can use my two keys now :+1:

**Comment by jerrywoo96** [comment] 2022-10-31 09:25
> You can change the key description from `Primary` to anything else using SQL. This will allow you to register a second key via the web UI with the default description, `Primary`.

@james-d-elliott I cannot find the table name and column which contains the value `Primary`.
@hleroy In which table did you find where the primary key was selected?

![image](https://user-images.githubusercontent.com/26324139/198975214-76474c2a-b3f4-46d7-9e21-1c80b6f4c6f4.png)

**Comment by james-d-elliott** [comment] 2022-10-31 11:34
You're not using a version that supports webauthn at all, if you did it'd have the `webauthn_devices` table, you're using one that's more than a year old (latest is not a version). 

1. This message and the [previous message](https://github.com/authelia/authelia/issues/275#issuecomment-1288176860) are the extent to which we're providing support on this until such a time as the actual feature is implemented in *most likely* 4.38.0. 
2. If this breaks anything you're on your own.
3. If this doesn't work you're on your own.
4. If it can't be figured out from these two messages then we suggest waiting until the release.

**Comment by smkent** [comment] 2022-11-02 07:34
Hi all! I have a number of thoughts around the existing authentication flow and how a settings UI including multiple key support might look.

I personally found Authelia's current flow around login and 2FA enrollment confusing. The authentication states are represented only within the inset part of the authentication pages. The existing `Method` button also serves multiple purposes:
* Selection of 2FA method when logging in
* Selection of 2FA enrollment method when prompted after password login, if not already enrolled in 2FA
* Selection of 2FA method to configure when fully logged in

IMO, the flow would be less confusing if the various login and signup states were more distinct. 2FA enrollment could be implemented as reusable components for use within otherwise independent UI flows for the above scenarios.

I spent some time making UI flow brainstorms/mockups by shuffling DOM elements around in my browser's dev tools. Below are some high level thoughts.

As a sidenote, I also found it confusing that email verification is required for each 2FA setup/change action. I'm not familiar with any other authentication system that verifies each action this way. The UI flow brainstorms below don't incorporate email verification for each step.

## Login flow

Here's the existing password prompt for reference:

![1-password_form](https://user-images.githubusercontent.com/2831985/199423889-937881a8-c0ae-4796-99d3-ab85a5468e63.png)

After successful password login, there are a number of possible states:

### 2FA required, and user is enrolled in 2FA

On the 2nd-factor authentication prompt, the method selector could live within the authentication prompt frame to make it clear. Google's login flow does something similar -- the user is prompted with their default method, but there's also a link to "try another way."

![2-2fa_configured_prompt](https://user-images.githubusercontent.com/2831985/199424030-22d6d240-69f7-4316-ba8a-f2cbc0b1397d.png)

### 2FA required, but user is not yet enrolled in 2FA

When requiring users to enroll in 2FA before completing login, the 2FA method options could be presented right on the prompt. Selecting a method would lead to a modal popup flow for the selected method to finish enrollment.

![2-2fa_enrollment_prompt](https://user-images.githubusercontent.com/2831985/199424423-a8953a86-9355-4417-a5a1-76c622b730ce.png)

#### Modal enrollment flow for security keys

The popup enrollment flow for WebAuthn could look something like this:

The flow would start with the existing key discovery prompt:

![2-2fa_modal_1](https://user-images.githubusercontent.com/2831985/199424633-ad625d88-9009-410c-b521-6f167ea20892.png)

Then, the user would be prompted for a name:

![2-2fa_register_key_name_prompt](https://user-images.githubusercontent.com/2831985/199424876-f893e504-3884-46d4-a8fa-5d4d70299ebb.png)

At this point the user would be logged in.

## Logged in landing page

Authelia's current landing page after successful 2FA login is a big green check mark with a 2FA registration/reset link at the bottom ("Lost your device?" for WebAuthn). The log out button and 2FA configuration method selector are outside of the main UI frame.

The landing page could be both simplified and be a launch point into a new account settings page / control panel (where 2FA methods could be configured, such as registering multiple WebAuthn devices).

This could look like one of the following:

![3-logged_in](https://user-images.githubusercontent.com/2831985/199425556-8a814670-77c1-424b-a252-5b70e0299bf8.png)

![3-logged_in_alt_2](https://user-images.githubusercontent.com/2831985/199425607-8cb1c1a4-f56e-409a-8ba8-6023480afef1.png)

### Account settings

Account settings could initially just contain the 2FA configuration options. In fact, the account settings page could simply be 2FA configuration until more types of settings are added in the future.

The 2FA configuration options here would launch into the same reusable enrollment flow components that the login flow 2FA enrollment UI would use.

Here's a quick sketch which would largely reuse the same login frame size:

![4-2fa_config_panel_alt_1](https://user-images.githubusercontent.com/2831985/199426027-d5e06c95-5e9e-49fa-a8e3-3bcc91ce04dc.png)

Alternatively, the settings page could be a visually expanded frame covering much / most of the viewport with room for more options.

Here's a sketch of a larger box size:

![4-2fa_config_panel_alt_2](https://user-images.githubusercontent.com/2831985/199426242-8e713539-ca1e-4e72-8693-11a7faed6974.png)

Here's a very simple copy-paste of the work-in-progress 2FA config UI from the [`feat-settings-ui` branch](https://github.com/authelia/authelia/tree/feat-settings-ui) just to show how a config panel might fit into the existing Authelia UI frame/style:

![4-2fa_config_panel_alt_2_composite](https://user-images.githubusercontent.com/2831985/199426507-72403194-3dc3-4383-87a1-7883cdde4ee5.png)

**Comment by james-d-elliott** [comment] 2022-11-02 08:32
Hi @smkent thanks for taking the time to draft all of this up. I think there are a few key areas I can think of to add to this that I can give at this time based on internal discussions with Amir and Clement, and/or personal thoughts. All of which I'm keen to hear your thoughts on.

1. I'll try to come up with some UI elements like you did in order to demonstrate some of this ideas. I also really appreciate your input as it helps us make sure we consider aspects like the usability.
2. The separation of concerns is relatively high on our list. Maintaining two areas to do the same action is not great for maintainability. As such the thought was that the registration of 2FA methods would be entirely relegated to the settings area. The settings area is going to be an inevitability and gives us more flexibility to move it away from the streamlined login portal.
    1. The need to configure a device would probably be linked to rather than immediately available within the portal itself (this partially addresses a portion of your concerns regarding the confusion).
    2. The first time registration could just be shown in the portal when needed.
    3. The ability to add an additional device that you've not registered yet could be shown in the method selections list if available as well, just ensuring that it is clearly distinguished from utilization of an existing method.
3. I think the idea was to add a settings/quick settings UI element on the top right represented by an icon or icon with text (this icon could at a later date be replaced by the users picture with a fallback to the MUI settings cog).
    1. It's fairly common to add this sort of thing here and we can just adjust the notification snackbar at this time.
    2. Examples of other elements that could exist in this area would be:
        1. a selection dialogue to locally (browser/device level) adjust the language  - probably a short term goal
        2. a selection dialogue to locally adjust the theme - probably a midterm goal
        3. settings link - immediate
        4. admin control panel link when implemented and available to the user - probably a long term goal
        5, logout link  - probably a short term goal
        6. switch account dialogue  - probably a long long term goal
4. I think removal of the header context from the top when in the settings context is probably a good move as this is primarily useful for the login flow. I feel like we can probably remove the logout link from it in fact and hide that behind the settings dialogue as it doesn't really add anything.
5. For context this will not be a settings area dedicated to 2FA settings. It will be all user controllable settings. Examples of other things users may control from here in the future:
    1. a selection dialogue to adjust the users preferred language (account default) - probably a short term goal
    2. a selection dialogue to adjust the users preferred theme (account default) - probably a midterm goal
    3. a selection dialogue to adjust the users preferred 2FA method (account default, and make the portal adjust it per browser/device) - probably a short term goal
    4. change password (with the current password known) - probably a mid term goal


@all-contributors please add @smkent for ideas

**Comment by james-d-elliott** [comment] 2022-11-02 08:32
https://github.com/all-contributors please add @smkent for ideas

**Comment by james-d-elliott** [comment] 2022-11-02 08:33
@all-contributors please add @smkent for ideas

**Comment by smkent** [comment] 2022-11-18 05:34
Work toward this is progressing along with a new settings UI. Multiple Webauthn devices per user is designed in https://github.com/authelia/authelia/issues/4366. Initial work in progress is in https://github.com/authelia/authelia/pull/4376.

**Comment by james-d-elliott** [comment] 2022-11-18 07:45
Yep! As already mentioned probably in this issue and the chat it will land in 4.38. A big thanks is in order to @smkent for working on this while we work on the rest of 4.38. it'll greatly speed up 4.38.

**Comment by smkent** [comment] 2022-11-29 04:01
Updated UI preview!

![more-preview](https://user-images.githubusercontent.com/2831985/204435742-38b9a3ba-e585-472d-b66b-409f29f099e9.png)

**Comment by pbek** [comment] 2022-11-29 06:52
That's awesome! Thank you very much!

**Comment by jpslv** [comment] 2023-01-19 11:05
Thank you all - excited for this feature!

**Comment by BirdInFire** [comment] 2023-07-28 22:52
I do not use authelia since a wile any progress on this one ? (5 years later maybe time no ?)

**Comment by james-d-elliott** [comment] 2023-07-28 22:59
Yes, linked the PR.

**Comment by BirdInFire** [comment] 2023-07-28 23:27
> Yes, linked the PR.

fair enough :), I will finally can remove authentik (since I do have 4 key, (2 device linked (Windows hello / Apple Touch ID), and 2 yubikey bio) the limit was a deal broker for me, and unlike authentik Authelia use less CPU.

**Comment by black-fake** [comment] 2023-09-15 07:48
> You can change the key description from `Primary` to anything else using SQL. This will allow you to register a second key via the web UI with the default description, `Primary`.

How can I "force" authelia to add a new hardware key? Is there a specific URL for that? Can't find anything in the docs ...

If I try `https://auth.mydomain.com/2fa/webauthn/register`, I just get redirected to the page where it says that I successfully authenticated ...
I also don't see any option to register a new key via gui.
The change of the description of my already registered key did work without problems.

**Comment by pinpox** [comment] 2023-09-28 09:15
I saw the linked PR was merged. Is there any plans for this to be released soon(-ish) ? Not sure if I should go through the hassle of running the 4.38 Pre-Release just for this or wait a few days for it to be properly released.

**Comment by ammoniak** [comment] 2023-09-28 09:37
The maintainer wrote somewhere (maybe in the blog?) that they are currently quite busy with work, etc. and don't have much time for Authelia. It was planned to be released in the beginning of this year, so it might be a few days or a few weeks from now...

@james-d-elliott Is there something we (the community) can do to help you?

**Comment by james-d-elliott** [comment] 2023-09-28 10:22
I will (hopefully) want some testing relatively soon so I can get some pointed feedback about specific things that need to be fixed. Post is [here](https://github.com/authelia/authelia/discussions/4813). It's also important to note there are massive improvements to OIDC and the whole `/api/verify` endpoint coming with this release too.

Nothing important to this specific feature has yet been merged however a lot of it has been completed, just working on some hopefully final touches. Mainly because adding multiple keys should also have a reasonable UX included (session can add new 2FA methods for a brief period rather than having to confirm each new method).

**Comment by james-d-elliott** [comment] 2023-09-28 10:29
Side note, the biggest part of this is indeed the changes to the registration process. It's quite extensive and has a direct impact on security so getting it correct is really important to me.

**Comment by pinpox** [comment] 2023-09-28 11:16
> It's also important to note there are massive improvements to OIDC

Not strictly related, but will this allow for authelia use other OIDC providers as backend in addition to it's own users? I have currently a mix of authelia and dex set up, to allow logging in with user accounts from ldap aswell as some specific github organisations (via OIDC). Would be awesome, if I could ditch dex.

**Comment by thiscantbeserious** [comment] 2024-02-10 11:46
Just pointing out - anyone still looking for a solution (since v4.38 is not officially out) 

v4.38.0-beta3 works great and has a proper UI for adding multiple keys!

All you have to do is use the correct tag for the docker container :hear_no_evil: 

![image](https://github.com/authelia/authelia/assets/34506214/46db136b-0871-4904-b9ae-71eaed35fa87)

**Comment by james-d-elliott** [comment] 2024-02-10 19:42
I'm sorry I appreciate the intent but there is a discussion covering specific instructions and the feedback avenue.

Users interested in the beta should disregard the warnings and instructions above and read the official instructions [here](https://github.com/authelia/authelia/discussions/categories/pre-release-feedback).

**Comment by thiscantbeserious** [comment] 2024-02-10 19:58
> I'm sorry I appreciate the intent but there is a discussion covering specific instructions and the feedback avenue. If people don't follow the official instructions ...
>
> Make a feedback discussion with the issues you had including logs and DB backend so we can tackle this before releasing.

Absolutely will do - already prepared the dumps and will try to reproduce it a second time just in case to make sure its not my mistake ...

Cheers!

**Closed** 2024-03-04 09:42 UTC
Labels: type/enhancement, priority/3/medium, status/needs-design, area/webauthn, area/ui
