### ISSUE TITLE
Map oidc scopes

### ISSUE THREAD

**Issue by riccardogiambra** [authelia/authelia#5323] opened 2023-04-26 18:23 UTC
### Description

Have the possibility to map an attribute into a scpecific oidc scope 

### Use Case

I'm using ldap as backend and i'm implementing the autologin for gitea through oidc. 
As gitea [doc](https://docs.gitea.io/en-us/config-cheat-sheet/#oauth2-client-oauth2_client) sais, the Username could be a scope called "nickname", but authelia can't provide this one. It could be usefull to configure custom scopes.
for example, when I declare a client i could have something like this: 
```    
    - id: gitea
       [...]
       scopes:
        - openid
        - profile
        - email
        - groups
        - username:nickname
```
where the row `- username:nickname` does exactly this mapping

### Pre-Submission Checklist

- [x] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)
- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment] 2023-04-26 21:02
This is a duplicate of #2868, and while it's a nice to have many OIDC clients allow users to define this claim arbitrarily, and the preferred_username claim  already exists and is the normative value for account creation.

**Closed by james-d-elliott** 2023-04-26 21:02 UTC
Labels: priority/4/normal, type/feature, status/needs-design
