### ISSUE TITLE
ReferenceError: Can't find variable: BroadcastChannel

### ISSUE THREAD

**Issue by lukasbuksa** [authelia/authelia#4009] opened 2022-09-13 21:08 UTC
### Description

The login page is not loading. It just shows a white screen and there are errors in the console (ReferenceError: Can't find variable: BroadcastChannel). This bug can be observed on some IOS devices - it doesn't matter what browser you use.

**Comment by LagManCZ** [comment] 2022-09-13 21:13
We are running Authelia version 4.36.7.
Authelia log shows:
level=info msg="Access to https://auth.example.com/ (method GET) is not authorized to user <anonymous>, responding with status code 302 with location redirect to https://auth.example.com?rd=https%3A%2F%2Ftest.example.com%2F&rm=GET" method=GET path=/api/verify remote_ip=

**Comment by nightah** [comment] 2022-09-13 23:27
> This bug can be observed on some IOS devices - it doesn't matter what browser you use.

Please provide additional details so we can attempt to reproduce this issue.
What devices can you confirm this behaviour on? What version of iOS?

**Comment by james-d-elliott** [comment] 2022-09-14 09:20
Looks like iOS only received support in 15.4: https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel#browser_compatibility

Note that the only browser on iOS is Safari, effectively.

**Comment by nightah** [comment] 2022-09-15 23:11
@lukasbuksa @LagManCZ could you please try the Docker tag `fix-web-safari-bcast`, this should resolve your issue.

Also would be good to understand and confirm that your version of iOS is < what is specified above.

**Comment by LagManCZ** [comment] 2022-09-17 13:10
Sorry for late reply,
we have tried to install Authelia via docker tag `fix-web-safari-bcast` and it works now.
Are there any disadvantages using this image (old Authelia version…) or it is just normal image with support for old iOS versions?

**Comment by nightah** [comment] 2022-09-17 13:27
There's no disadvantage other than when it's merged to master the tag will disappear. It'll be in the next patch release so keep an eye out and update soon.

**Comment by LagManCZ** [comment] 2022-09-17 17:58
Great news, thanks for your help and quick resolution of the problem!
We'll keep an eye on new patch release. You may close this issue.

**Closed** 2022-09-19 04:49 UTC
Labels: priority/4/normal, status/ready, type/bug/third-party
