### ISSUE TITLE
Protect multiple domains with Authelia and/or set rules for dynamic IP-s

### ISSUE THREAD

**Issue by mqmq0** [authelia/authelia#1286] opened 2020-08-25 19:09 UTC
Hello Folks,

Help me out how could I protect multiple domains with Authelia, or rather how could I setup rules for more then one domain.

My usecase: I have a public domain and couple subdomains for me services. myapp.domain.com redirects nicely to authelia.domain.com, gets authenticated and directes back.

Now I want to introduce local domains on my own network mainly because I cannot setup rules otherwise, since my routers IP address always changing, partially because this way I can spare one hop in a request (the router).

My authelia.conf looks like this right now:
```
access_control:
  default_policy: two_factor

  rules:
    - domain: myapp.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24
    - domain: myapp.lo.cal
      policy: one_factor
      networks:
      - 192.168.0.0/24


session:
  name: authelia_session

  secret: yep-a-secret

  expiration: 1h

  inactivity: 5m

  remember_me_duration: 1M

  domain: domain.com
  domain: lo.cal
```
But this way, I just cannot get through the first factor even:
```

INFO[0018] Access to https://myapp.lo.cal/ is not authorized to user , sending 401 response  method=GET path=/api/verify remote_ip=192.168.0.111
DEBU[0025] Credentials validation of user MyUser is ok    method=POST path=/api/firstfactor remote_ip=192.168.0.111
DEBU[0025] Mark authentication attempt made by user MyUser  method=POST path=/api/firstfactor remote_ip=192.168.0.111
DEBU[0025] Required level for the URL https://myapp.lo.cal/ is 1  method=POST path=/api/firstfactor remote_ip=192.168.0.111
DEBU[0025] Redirection URL https://myapp.lo.cal/ is safe  method=POST path=/api/firstfactor remote_ip=192.168.0.111
INFO[0025] Access to https://myapp.lo.cal/ is not authorized to user , sending 401 response  method=GET path=/api/verify remote_ip=192.168.0.111
```
If I try like this:

`  domain: domain.com lo.cal`

Then I get another error, and still do not get through:

```
ERRO[0003] The target URL https://myapp.lo.cal/ is not under the protected domain domain.com myapp.lo.cal  method=GET path=/api/verify remote_ip=192.168.0.111 stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:395     VerifyGet.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.1.1/router.go:288                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.12.0/server.go:2087                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                 goexit"
DEBU[0009] Credentials validation of user MyUser is ok    method=POST path=/api/firstfactor remote_ip=192.168.0.111
DEBU[0009] Mark authentication attempt made by user MyUser  method=POST path=/api/firstfactor remote_ip=192.168.0.111
DEBU[0009] Required level for the URL https://myapp.lo.cal/ is 1  method=POST path=/api/firstfactor remote_ip=192.168.0.111

```

Or if simple I just list one domain in the session part:

```
INFO[0937] Access to https://myapp.domain.com/update is not authorized to user , sending 401 response  method=GET path=/api/verify remote_ip=94.21.XXX.130
ERRO[1200] The target URL https://myapp.lo.cal/ is not under the protected domain domain.com  method=GET path=/api/verify remote_ip=192.168.0.111 stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:395     VerifyGet.func1\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:49 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.1.1/router.go:288                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.12.0/server.go:2087                       (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:223                    (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.12.0/workerpool.go:195                    (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                 goexit"
```

And here I'm out of ideas.
As a workaround I though about running another instace of Authelia, but then I would need another set of server blocks in nginx for all my apps... this could get complicated very quickly so I rather not. 

SO my question:
-How do I protect two domains
or
-How do I set access rules for dynamic IP

**Comment by james-d-elliott** [comment] 2020-08-26 00:10
The problem is the web itself does not allow for this to happen. Cookies can only be set and accessed by the domain that creates them. So if you have example.com and example.net you cannot set or read a cookie for example.net on an Authelia instance on example.com.

What I'd recommend is learning how LDAP works, and hooking two instances up to one LDAP (same usernames and passwords).

**Comment by mqmq0** [comment] 2020-08-26 19:12
Its not necessarily two domains. I could (actually I did) setup local dns record for authelia, like authelia.lo.cal
Like this, requests from myapp.lo.cal could be redirected to authelia.lo.cal, likewise outside request would behave the some with domain.com. 

Password backend not a problem, I could use LDAP, but a simple file is more than enough for me, and I can add that file to multiple configs. 
The problem comes with the nginx auth.conf, where I have the `error_page 401 =302 https://authelia.domain.com/?rd=$target_url;`.
With two authelia instances, I need to create another auth.conf, another server block for all my apps using that conf... and thats complicated.

What about my other idea dynamic IP address as an Access Rule. I mean there is DDNS to make dynamic IP-s sort-of static, could this  be possible with some kind of reverese DNS lookup?

If I get this correctly, neither is supported right now, its not just me not finding the correct settings?

**Comment by sorano** [comment] 2020-08-27 09:51
> What about my other idea dynamic IP address as an Access Rule. I mean there is DDNS to make dynamic IP-s sort-of static, could this be possible with some kind of reverese DNS lookup?

In this case how would you suggest that Authelia knows if a public IP is dynamic or static?
That kind of information is up to each ISP to assign.

A possible solution for you could be to add the whole WAN subnet(s) that your ISP(s) assigns under Authelia networks config.

Also reverse DNS lookups (PTR records, IP --> DNS) on dynamic IP's is normally nothing that the end user has control over and is configured in a generic way by the ISP.

So I would say dynamic IP isn't the correct terminology to use here.

However, making a forward DNS lookup to match a hostname to an IP? Now we're talking.

**Comment by james-d-elliott** [comment] 2020-08-27 21:28
It's not supported to lookup the IP of a network via DNS no. As far as a solution, if it were me I'd assign my router to use the domain suffix of the external domain, and manually add records; if it was supported.

**Comment by sorano** [comment] 2020-08-28 08:30
> It's not supported to lookup the IP of a network via DNS no. As far as a solution, if it were me I'd assign my router to use the domain suffix of the external domain, and manually add records; if it was supported.

Agreed. Solving it in the router is the most feasible solution. Also a VPN between the two sites could work.

**Comment by nightah** [comment] 2020-11-11 12:31
Closing this off as the first part is covered in #1198.

**Closed by nightah** 2020-11-11 12:31 UTC

**Comment by alexw1982** [comment] 2021-01-29 21:01
> 
> 
> The problem is the web itself does not allow for this to happen. Cookies can only be set and accessed by the domain that creates them. So if you have example.com and example.net you cannot set or read a cookie for example.net on an Authelia instance on example.com.

I am running into the same issue but on two subdomains - is that also supposed to happen? 

my authelia.log basically looks the same. A search result on the first subdomain links to a page on the second subdomain:

Log extract
```time="2021-01-29T19:58:42+01:00" level=debug msg="Mark authentication attempt made by user alex" method=POST path=/api/firstfactor remote_ip=87.123.122.212
time="2021-01-29T19:58:42+01:00" level=debug msg="Credentials validation of user alex is ok" method=POST path=/api/firstfactor remote_ip=87.123.122.212
time="2021-01-29T19:58:42+01:00" level=debug msg="Required level for the URL https://search.mydomain.de/ is 1" method=POST path=/api/firstfactor remote_ip=87.123.122.212
time="2021-01-29T19:58:42+01:00" level=debug msg="Redirection URL https://search.mydomain.com/ is safe" method=POST path=/api/firstfactor remote_ip=87.123.122.212
time="2021-01-29T19:58:54+01:00" level=info msg="Access to https://yt.mydomain.com/channel/UC2GIHZpQiJy-8286f4lj_cg?quality=dash&autoplay=1 is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip=87.123.122.212
time="2021-01-29T19:59:06+01:00" level=info msg="Access to https://search.mydomain.com/autocomplete is not authorized to user , sending 401 response" method=GET path=/api/verify remote_ip```
