### ISSUE TITLE
Access Control help

### ISSUE THREAD

**Issue by mqmq0** [authelia/authelia#834] opened 2020-04-07 20:27 UTC
Hello Good People of Authelia,

I'm using this wonderful tool since January, just recently updated the the latest release and now I decided to set up some Access Control rules but I just cannot figure out what am I doing wrong.
What I want to achieve that I do not have to use the second factor when "I'm home" e.g. from LAN
Let me show you my full Config.yml right now
```
root@asd:/var/www/public_html# cat /etc/authelia/config.yml

host: 0.0.0.0
port: 9091

log_level: debug

jwt_secret: asdasd

default_redirection_url: https://proteced.domain.com/


totp:
  issuer: asd
  period: 30
  skew: 1

duo_api:
  hostname: asdasd
  integration_key: asdasd
  secret_key: asdasd


authentication_backend:
  file:
     path: /etc/authelia/users.yml


access_control:
  default_policy: two_factor

    rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24

session:
  name: authelia_session

  secret: asasd

  expiration: 1h

  inactivity: 5m

  remember_me_duration: 1M

  domain: domain.com


regulation:
  max_retries: 3

  find_time: 2m

  ban_time: 5m

storage:
   local:
    path: /etc/authelia/db.sqlite3

notifier:

    smtp:
     username: asd@gmail.com
     password: asd
     host: smtp.gmail.com
     port: 587
     sender: asd@gmail.com
     secure: false
```
Everything works fine until I add the 'rules: ' part to the config.
Either I got the logic wrong, or I'm just making some kind of typo, bad indentation or something...

**Comment by clems4ever** [comment] 2020-04-07 22:01
Hello @mqmq0 , we need more info on what kind of error you're facing to help you out. Can you elaborate by describing your scenario and tell us what's the actual issue?

I think some logs in debug mode would be useful too since your config looks good to me.

**Comment by nightah** [comment] 2020-04-07 23:49
@mqmq0 it does look to me like your indenting is slightly off in the configuration you have provided, you need to outdent rules so that this:
```
access_control:
  default_policy: two_factor

    rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24
```

Becomes like this:
```
access_control:
  default_policy: two_factor

  rules:
    - domain: protected.domain.com
      policy: one_factor
      networks:
      - 192.168.0.0/24
```

**Comment by mqmq0** [comment] 2020-04-08 07:50
Wonderful, now its works! I was pretty sure I'm making some kind of pity error.

Now it's starts up again, but still ask for the 2nd factor. I enabled logging to see what happens and I suspect the problem is with the **remote_ip**

```
time="2020-04-08T08:54:31+02:00" level=debug msg="Using X-Original-URL header content as targeted site URL" method=GET path=/api/verify remote_ip=127.0.0.1
time="2020-04-08T08:54:31+02:00" level=error msg="Access to https://protected.domain.com/ is not authorized to user " method=GET path=/api/verify remote_ip=127.0.0.1 stack="github.com/authelia/authelia/internal/handlers/handler_verify.go:270     VerifyGet\ngithub.com/authelia/authelia/internal/middlewares/authelia_context.go:47 AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v0.7.0/router.go:443                          (*Router).Handler\ngithub.com/authelia/authelia/internal/middlewares/log_request.go:14      LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.9.0/server.go:2041                        (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.9.0/workerpool.go:223                     (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.9.0/workerpool.go:195                     (*workerPool).getCh.func1\nruntime/asm_amd64.s:1373                                                 goexit"

```
How do I make Authelia to recognise the IP of my request? 
If I'm correct, its something with Nginx. I'm using the configs from here: https://docs.authelia.com/deployment/supported-proxies/nginx.html
Proxy.conf has 

`set_real_ip_from 192.168.0.0/24;`

but as it seems its not working. 
Or I'm getting something wrong completely.

**Comment by nightah** [comment] 2020-04-08 08:03
This may be intended depending on the Architecture, are you visiting Authelia from the same machine that hosts nginx?

Could you please provide full nginx configuration for both your Authelia site, the protected endpoint and any of the supplementary nginx configuration.

**Comment by mqmq0** [comment] 2020-04-08 08:25
So my setup is: Rpi running Nginx, Small X86 machine running Authelia and a [Code-Server](https://github.com/cdr/code-server) and I'm accessing from my laptop/phone. All on same LAN, 192.168.0.0/24 (later on I want to involve an OpenVPN lan aswell)

Nginx configs:

```
Authelia.conf

# Virtual endpoint created by nginx to forward auth requests.
location /authelia {
    internal;
    set $upstream_authelia http://192.168.0.109:9091/api/verify;
    proxy_pass_request_body off;
    proxy_pass $upstream_authelia;
    proxy_set_header Content-Length "";

    # Timeout if the real server is dead
    proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

    # [REQUIRED] Needed by Authelia to check authorizations of the resource.
    # Provide either X-Original-URL and X-Forwarded-Proto or
    # X-Forwarded-Proto, X-Forwarded-Host and X-Forwarded-Uri or both.
    # Those headers will be used by Authelia to deduce the target url of the user.
    # Basic Proxy Config
    client_body_buffer_size 128k;
    proxy_set_header Host $host;
    proxy_set_header X-Original-URL $scheme://$http_host$request_uri;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-Host $http_host;
    proxy_set_header X-Forwarded-Uri $request_uri;
    proxy_set_header X-Forwarded-Ssl on;
    proxy_redirect  http://  $scheme://;
    proxy_http_version 1.1;
    proxy_set_header Connection "";
    proxy_cache_bypass $cookie_session;
    proxy_no_cache $cookie_session;
    proxy_buffers 4 32k;

    # Advanced Proxy Config
    send_timeout 5m;
    proxy_read_timeout 240;
    proxy_send_timeout 240;
    proxy_connect_timeout 240;
}


```
```
auth.conf

# Basic Authelia Config
# Send a subsequent request to Authelia to verify if the user is authenticated
# and has the right permissions to access the resource.
auth_request /authelia;
# Set the `target_url` variable based on the request. It will be used to build the portal
# URL with the correct redirection parameter.
auth_request_set $target_url $scheme://$http_host$request_uri;
# Set the X-Forwarded-User and X-Forwarded-Groups with the headers
# returned by Authelia for the backends which can consume them.
# This is not safe, as the backend must make sure that they come from the
# proxy. In the future, it's gonna be safe to just use OAuth.
auth_request_set $user $upstream_http_remote_user;
auth_request_set $groups $upstream_http_remote_groups;
proxy_set_header X-Forwarded-User $user;
proxy_set_header X-Forwarded-Groups $groups;
# If Authelia returns 401, then nginx redirects the user to the login portal.
# If it returns 200, then the request pass through to the backend.
# For other type of errors, nginx will handle them as usual.
error_page 401 =302 https://authelia.domain.com/?rd=$target_url;


```
```
proxy.conf

client_body_buffer_size 128k;

#Timeout if the real server is dead
proxy_next_upstream error timeout invalid_header http_500 http_502 http_503;

# Advanced Proxy Config
send_timeout 5m;
proxy_read_timeout 360;
proxy_send_timeout 360;
proxy_connect_timeout 360;

# Basic Proxy Config
proxy_set_header Host $host;
proxy_set_header X-Real-IP $remote_addr;
proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
proxy_set_header X-Forwarded-Proto $scheme;
proxy_set_header X-Forwarded-Host $http_host;
proxy_set_header X-Forwarded-Uri $request_uri;
proxy_set_header X-Forwarded-Ssl on;
proxy_redirect  http://  $scheme://;
proxy_http_version 1.1;
proxy_set_header Connection "";
proxy_cache_bypass $cookie_session;
proxy_no_cache $cookie_session;
proxy_buffers 64 256k;

# If behind reverse proxy, forwards the correct IP
set_real_ip_from 10.0.0.0/8;
set_real_ip_from 172.0.0.0/8;
set_real_ip_from 192.168.0.0/24;
set_real_ip_from fc00::/7;
real_ip_header X-Forwarded-For;
real_ip_recursive on;


```
```
authelia portal

server {
    server_name authelia.domain.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    server_name authelia.domain.com;
    listen 4545 ssl http2;  //port sharing with OpenVPN

        ssl_certificate /etc/letsencrypt/live/authelia.domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/authelia.domain.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    location / {
        set $upstream_authelia http://192.168.0.109:9091;
        proxy_pass $upstream_authelia;
        include proxy.conf;
    }
}


```
```
Protected portal

server {
    listen 80;
    server_name protected.domain.com;

    location / {
        include default_headers;
        return 301 https://$server_name$request_uri;
    }
}

server {
    server_name protected.domain.com;
    listen 4545 ssl http2; //port sharing with OpenVPN

        ssl_certificate /etc/letsencrypt/live/protected.domain.com/fullchain.pem; # managed by Certbot
        ssl_certificate_key /etc/letsencrypt/live/protected.domain.com/privkey.pem; # managed by Certbot
        include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
        ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

    include authelia.conf;

    location / {
        set $upstream_nextcloud http://192.168.0.109:8443;
        proxy_pass $upstream_nextcloud;
        include auth.conf;
        include proxy.conf;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection upgrade;
        proxy_set_header Accept-Encoding gzip;
    }
}

```

**Comment by nightah** [comment] 2020-04-08 08:32
Are nginx and authelia run in Docker containers?

**Comment by mqmq0** [comment] 2020-04-08 08:48
Nope, authelia is directly downloaded from /releases/latest and nginx is from ubuntu repo.

**Comment by nightah** [comment] 2020-04-08 09:04
Ah so you're running both baremetal, okay got the corresponding nginx logs too?

**Comment by mqmq0** [comment] 2020-04-08 09:37
Yes. error.log has nothing.
access.log from my last attempt:

```
127.0.0.1 - - [08/Apr/2020:11:26:55 +0200] "GET /2fa/one-time-password?rd=https%3A%2F%2Fprotected.domain.com%2F HTTP/2.0" 200 1107 "-" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:16 +0200] "GET / HTTP/2.0" 302 170 "-" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:16 +0200] "GET /?rd=https://protected.domain.com/ HTTP/2.0" 200 1086 "-" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:16 +0200] "GET /static/css/main.d2ee2d92.chunk.css HTTP/2.0" 200 2687 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:16 +0200] "GET /static/js/main.dcc9f368.chunk.js HTTP/2.0" 200 54787 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:16 +0200] "GET /static/js/2.9b45f875.chunk.js HTTP/2.0" 200 471546 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:17 +0200] "GET /api/state HTTP/2.0" 200 114 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:17 +0200] "GET /api/configuration HTTP/2.0" 200 65 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:17 +0200] "GET /favicon.ico HTTP/2.0" 200 1107 "https://authelia.domain.com/?rd=https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:20 +0200] "POST /api/firstfactor HTTP/2.0" 200 15 "https://authelia.domain.com/?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:20 +0200] "GET /api/state HTTP/2.0" 200 119 "https://authelia.domain.com/?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:20 +0200] "GET /api/user/info HTTP/2.0" 200 72 "https://authelia.domain.com/?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:20 +0200] "GET /api/configuration/extended HTTP/2.0" 200 119 "https://authelia.domain.com/?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "POST /api/secondfactor/totp HTTP/2.0" 200 60 "https://authelia.domain.com/2fa/one-time-password?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "GET / HTTP/2.0" 200 2242 "https://authelia.domain.com/2fa/one-time-password?rd=https%3A%2F%2Fprotected.domain.com%2F" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/loader.js HTTP/2.0" 200 33514 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/node_modules/semver-umd/lib/semver-umd.js HTTP/2.0" 200 119591 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/workbench.web.api.nls.js HTTP/2.0" 200 239239 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:32 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/node_modules/@microsoft/applicationinsights-web/dist/applicationinsights-web.js HTTP/2.0" 200 318362 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:33 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/workbench.web.api.css HTTP/2.0" 200 455511 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:33 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/workbench.web.api.js HTTP/2.0" 200 5848423 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:35 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/code/browser/workbench/workbench.js HTTP/2.0" 200 4070 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:36 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js HTTP/2.0" 200 728 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:36 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/keybinding/browser/keyboardLayouts/layout.contribution.linux.js HTTP/2.0" 200 18864 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:36 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/base/browser/ui/octiconLabel/octicons/octicons.ttf?1829db8570ee0fa5a4bef3bb41d5f62e HTTP/2.0" 200 35428 "https://protected.domain.com/static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/workbench.web.api.css" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:36 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/browser/parts/editor/media/letterpress-dark.svg HTTP/2.0" 200 1917 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:36 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/base/browser/ui/codiconLabel/codicon/codicon.ttf?10ac421d405314bb3250169d97fc2c62 HTTP/2.0" 200 52620 "https://protected.domain.com/static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/workbench.web.api.css" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /vscode-remote-resource?path=%2Froot%2F.local%2Fshare%2Fcode-server%2Fextensions%2Fauchenberg.vscode-browser-preview-0.5.9%2Fresources%2Ficon.svg&tkn= HTTP/2.0" 200 1438 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/extensions/worker/extensionHostWorker.js HTTP/2.0" 200 1668715 "https://protected.domain.com/static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/extensions/worker/extensionHostWorker.nls.js HTTP/2.0" 200 14542 "https://protected.domain.com/static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/services/extensions/worker/extensionHostWorkerMain.js" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/node_modules/vscode-textmate/release/main.js HTTP/2.0" 200 142115 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /vscode-remote-resource?path=%2Fsrc%2Fbuild%2Fcode-server2.1692-vsc1.39.2-linux-x86_64-built%2Fextensions%2Ftheme-seti%2Ficons%2Fseti.woff&tkn= HTTP/2.0" 200 34420 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/node_modules/onigasm-umd/release/main.js HTTP/2.0" 200 48730 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:37 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/node_modules/onigasm-umd/release/onigasm.wasm HTTP/2.0" 200 596643 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:40 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/base/worker/workerMain.js HTTP/2.0" 200 139514 "https://protected.domain.com/" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:27:40 +0200] "GET /static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/workbench/contrib/output/common/outputLinkComputer.js HTTP/2.0" 200 42616 "https://protected.domain.com/static-e14362f3224c101585a26bf7ee5fa6e3bf425046/out/vs/base/worker/workerMain.js" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:28:43 +0200] "GET /?reconnectionToken=3e45d008-3829-4a00-87c0-700e176e7d89&reconnection=false&skipWebSocketFrames=false HTTP/1.1" 101 1812254 "-" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
127.0.0.1 - - [08/Apr/2020:11:28:43 +0200] "GET /?reconnectionToken=2ec3d045-1045-4245-821e-13ce05c229f0&reconnection=false&skipWebSocketFrames=false HTTP/1.1" 101 44578 "-" "Mozilla/5.0 (Linux; Android 10; H8324) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.96 Mobile Safari/537.36"
```
Here it's also clear that the origin of my request is 127.0.0.1 for some reason, but it was from my phone, LAN, no-vpn even.

**Comment by nightah** [comment] 2020-04-08 10:20
Fact that nginx thinks all your traffic leads me to believe it's either network related, or another app, is there anything in front of nginx?

**Comment by mqmq0** [comment] 2020-04-08 10:32
Indeed, there is an OpenVPN instance port sharing with Nginx 
/etc/openvpn/server.conf
```
# Which TCP/UDP port should OpenVPN listen on?
# If you want to run multiple OpenVPN instances
# on the same machine, use a different port
# number for each one.  You will need to
# open up this port on your firewall.
port 443
port-share 127.0.0.1 4545
# TCP or UDP server?
proto tcp
```


I have to host OpenVPN on 443 in order to avoid firewall rules... but okay I see the problem now, and probably its not with the sample config from the Docs. 
Let me dig into this.

**Comment by nightah** [comment] 2020-04-08 11:01
The issue is because all the traffic is coming from OpenVPN to nginx and that's local traffic so you're losing the originating IP address.

I would recommend putting your nginx directly on 80/443 and exposing OpenVPN on a different port.
If that's not feasible and you want to continue port sharing look at: https://jarrousse.org/getting-openvpn-and-nginx-to-share-port-443/.

Given the issue is outside of Authelia I'm going to close this off.

**Closed by nightah** 2020-04-08 11:01 UTC
Labels: Integration Issue, P2, Question
