### ISSUE TITLE
Pass additional headers from LDAP attributes

### ISSUE THREAD

**Issue by laurivosandi** [authelia/authelia#1386] opened 2020-10-18 09:53 UTC
I see currently Remote-User and Remote-Groups headers passed to the backend. For many usecases the backend would still need to talk to eg LDAP to fetch email address or full name. It would be great if Authelia could pull those bits as well and have them passed via Remote-* headers. Maybe a generic mapping mechanism would be useful. This would allow unrooting LDAP code from backends, simplify backend design, improve security due to reduced count of service accounts and much more.

**Comment by nightah** [comment] 2020-10-18 11:02
Duplicate of #1376.

**Closed** 2020-10-18 11:03 UTC
