### ISSUE TITLE
Create a web ui with management system

### ISSUE THREAD

**Issue by JVT038** [authelia/authelia#1953] opened 2021-04-27 12:16 UTC
### Description
It would be nice to have a webui where the admin can manage all users, manage the configurations

### Use Case
If the admin changes a setting in the UI, it will automatically be changed in `configurations.yml` or if the admin changes an user, it will automatically change `users_database.yml`

**Comment by nightah** [comment] 2021-05-04 23:21
Duplicate of #974.

**Closed by nightah** 2021-05-04 23:21 UTC
Labels: Feature Request
