### ISSUE TITLE
error getting user state

### ISSUE THREAD

**Issue by redwiz666** [authelia/authelia#1191] opened 2020-07-10 01:04 UTC
I setup authelia today using docker. When i go to the auth page I get the error "There was an issue fetching the current user state". When looking at the network inspection in firefox I see that I get 404 for /api/state. I am currently using mySQL database for users but am also getting the same error when using a file storage.

**Comment by ljohnson20** [comment] 2020-07-10 03:46
I was running into this same issue! I might have fixed it but I'm still not all the way there with the setup. I'm using Linux server io's lets encrypt container which utilizes nginx. My Authelia is set up using these [instructions](https://github.com/ibracorp/authelia) (I'm on an Unraid server which might make a difference)

On to the fix! The subdomain that was having issues was radarr which also had an api location set up in the nginx config file. So mine was `location ~ (/radarr)?/api` and I had to comment that whole block out. After that, I no longer got the "current user state" error.

I unfortunately still can't get it to redirect to Authelia when I first visit the site. I have to manually type in radarr.mydomain.org/authelia to get to the login but then it won't redirect after authenticating either. Let me know if you get it working I would love to get this properly set up!

**Comment by ljohnson20** [comment] 2020-07-10 04:07
Quick update commenting out that API location block for radarr fixed all my issues! It now redirects when I first access the site and goes back to radarr once I've authenticated.

I'm assuming (I'm still pretty new to this) that `~ (/radarr)?/api` looks for anything starting with radarr and ends with api. Since Authelia uses radarr.mydomain.org/authelia/api for the state, configuration, and user it gets mixed up and can't complete correctly. By commenting out that location though my guess is the radarr api cannot be accessed via the domain but at least the site works. If anyone has a workaround for this I would be interested.

**Comment by redwiz666** [comment] 2020-07-11 18:11
Thanks i will take a look. Im using traefik 2 but for radarr I have a similar rule that looks in the header for redirect. The odd think is if I use local ips everything seems to work. Im stsrting to think its a traefik 2 issue

**Comment by nightah** [comment] 2020-07-13 04:32
@ljohnson20 the issue you were facing was resolved upstream when I notified the LSIO team back in June with the following commit: https://github.com/linuxserver/docker-letsencrypt/commit/4fe3770361061b40a016823a884de23591e3376c#diff-c34738eb0c95fd83a24d12679c6dcb36.

You can just delete your `authelia-server.conf` and it will regenerate with the new one accordingly (assuming you're running an up-to-date letsencrypt container).

@redwiz666 can you please provide outputs of your Traefik/Docker configuration including your middleware definitions for the Authelia container and your protected endpoint?

Does the error appear upon first visting the auth portal, or on redirect? If you can detail your workflow and when you experience the issue we can help out further.

**Comment by nightah** [comment] 2020-07-14 08:36
@redwiz666 there was a regression in [Traefik v2.2.2](https://github.com/containous/traefik/issues/7020) which seems to have broke a lot of users setups.

Can you please try roll back to 2.2.1 and test again?

**Comment by nightah** [comment] 2020-07-24 00:56
@redwiz666 I'm closing this issue as I believe the issue is likely going to be related to the Traefik upstream issue.

If you still haven't been able to solve your issue please provide the information requested above and we will re-open the issue.

**Closed by nightah** 2020-07-24 00:56 UTC
