### ISSUE TITLE
Failed to register device

### ISSUE THREAD

**Issue by NiTRoeSE** [authelia/authelia#3046] opened 2022-03-22 13:12 UTC
### Description

Hi,
we use authelia running in docker-compose stack with redis and postgresql container with a nginx reverse proxy for over a year now. Our user backend is ldap.
we never had any problem to register new totp devices, but now we have. :(

We didn't changed anything in configuration and just updated the container with new released images a couple of times.

I can't say exactly when the error first occurred, but now every user who wants to register a new TOTP device gets the following error message after clicking on the link which was send out from authelia via mail:

**Failed to register device, the provided link is expired or has already been used...** and a qr code is not generated.

( Yes, the users use same device and browser while registration and use the links within 2 minutes after they get it via mail )

In authelia logs we get the following error:

`time="2022-03-22T13:37:52+01:00" level=error msg="the token has already been consumed" method=POST path=/api/secondfactor/totp/identity/finish remote_ip=172.20.1.1 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:183 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15   RequireFirstFactor.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52       AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.6/router.go:414                                   (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14            LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.34.0/server.go:2341                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                          goexit"`

In browser console the error which is shown is:

Error: Failed POST to /api/secondfactor/totp/identity/finish. Code: 200. Message: Operation failed

### Expected Behaviour

A working totp registration.

Thanks in advanced!

**Comment by NiTRoeSE** [comment] 2022-03-22 13:43
Additional we have the following error in logs just before "the token has already been consumed" error message:

`time="2022-03-22T13:37:12+01:00" level=error msg="unable to save TOTP secret in DB: error upserting TOTP configuration for user 'testuser': ERROR: duplicate key value violates unique constraint \"totp_configurations_pkey1\" (SQLSTATE 23505)" method=POST path=/api/secondfactor/totp/identity/finish remote_ip=172.20.1.1 stack="github.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:61       (*AutheliaCtx).Error\ngithub.com/authelia/authelia/v4/internal/handlers/handler_register_totp.go:50     secondFactorTOTPIdentityFinish\ngithub.com/authelia/authelia/v4/internal/middlewares/identity_verification.go:210 IdentityVerificationFinish.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/require_first_factor.go:15   RequireFirstFactor.func1\ngithub.com/authelia/authelia/v4/internal/middlewares/authelia_context.go:52       AutheliaMiddleware.func1.1\ngithub.com/fasthttp/router@v1.4.6/router.go:414                                   (*Router).Handler\ngithub.com/authelia/authelia/v4/internal/middlewares/log_request.go:14            LogRequestMiddleware.func1\ngithub.com/valyala/fasthttp@v1.34.0/server.go:2341                                (*Server).serveConn\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:224                             (*workerPool).workerFunc\ngithub.com/valyala/fasthttp@v1.34.0/workerpool.go:196                             (*workerPool).getCh.func1\nruntime/asm_amd64.s:1581                                                          goexit"`

**Comment by james-d-elliott** [comment] 2022-03-22 21:57
Version, and SQL backend?

**Comment by NiTRoeSE** [comment] 2022-03-23 07:32
> Version, and SQL backend?

- postgres (PostgreSQL) 13.6 --> Dockerimage " postgres:13-alpine" 
- authelia version v4.34.5 --> Dockerimage "latest"

**Comment by james-d-elliott** [comment] 2022-03-23 21:28
Could you show the tables in the database, and the columns in the totp_configurations table? Something strange that I can't replicate is occurring.

**Comment by NiTRoeSE** [comment] 2022-03-25 08:05
> Could you show the tables in the database, and the columns in the totp_configurations table? Something strange that I can't replicate is occurring.

I want to help but there are a lot of sensitive data in it, i send it via personal message...

PS: I made a simple test --> copied the docker-compose project, emptied the DB volume and startet the stack with an empty database so new one is initialized --> problem solved.
So its of course a database problem, interesting we never had an db error message or something else after updates.

**Comment by james-d-elliott** [comment] 2022-03-25 08:11
You can, I'm just looking for the structure itself though. Also if you'd like for me to attempt to repair the database schema you can reach me on Matrix or Discord here: https://github.com/authelia/authelia#contact-options

I'm somewhat curious what went wrong, it's never been an issue for me during upgrades. Only things I can think of being the cause are if you ever used master or a branch with schema changes prior to release (i.e. feat-webauthn). It is possible that the upgrade was interrupted at the wrong moment and it caused this issue, but that seems so very unlikely.

**Comment by james-d-elliott** [comment] 2022-03-25 10:35
Resolved via chat. Was an issue with pgsql storing the wrong next sequence value. Script which fixed it (postgres only) to follow. It should only be used when the error `unable to save TOTP secret in DB: error upserting TOTP configuration for user 'testuser': ERROR: duplicate key value violates unique constraint \"totp_configurations_pkey1\" (SQLSTATE 23505)` and I'd recommend talking to us to verify the issue before you do so.

Column Query:

```sql
\d+ totp_configurations
```

Use the index name value from the default value for the id column instead of `totp_configurations_id_seq1` though it should look similar:

```sql
SELECT nextval('totp_configurations_id_seq1`);
```

Repair Query with Backup:

```sql
ALTER TABLE totp_configurations RENAME TO _bkp_SERIAL_CORRUPT_totp_configurations;

CREATE TABLE totp_configurations (
    id SERIAL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    last_used_at TIMESTAMP WITH TIME ZONE NULL DEFAULT NULL,
    username VARCHAR(100) NOT NULL,
    issuer VARCHAR(100),
    algorithm VARCHAR(6) NOT NULL DEFAULT 'SHA1',
    digits INTEGER NOT NULL DEFAULT 6,
    period INTEGER NOT NULL DEFAULT 30,
    secret BYTEA NOT NULL,
    PRIMARY KEY (id),
    UNIQUE (username)
);

INSERT INTO totp_configurations (created_at, last_used_at, username, issuer, algorithm, digits, period, secret)
SELECT created_at, last_used_at, username, issuer, algorithm, digits, period, secret
FROM _bkp_SERIAL_CORRUPT_totp_configurations
ORDER BY id;
```

**Closed by james-d-elliott** 2022-03-25 10:35 UTC
Labels: Possible Bug
