### ISSUE TITLE
WebAuthn: Apple Passkey Support

### ISSUE THREAD

**Issue by adrw** [authelia/authelia#3787] opened 2022-08-03 14:27 UTC
## Feature Request

Apple has announced a new login API using public/private keys to support password-less logins. Will Authelia consider integrating with it as a login option?

https://developer.apple.com/passkeys/

**Comment by james-d-elliott** [comment] 2022-08-03 16:02
This is WebAuthn which has existed since 2016, Apple didn't invent anything here really. WebAuthn is backed by public/private keys, Apple PassKeys just transfers the private key via cloud infrastructure. I don't believe though will investigate at a much later date if there are any special API's for this, however if there are it's likely going to be a very low priority.

It's likely they're platform authenticators however: #2761

Regarding how I *THINK* we will end up supporting them it's via that FR there. We will possibly take steps to prevent their use  or limit their use to passwordless auth #2827 that can be turned off via configuration (probably via AAGUID filtering). The rational for this is allowing their transfer effectively means the physical aspect is effectively removed making it almost a `something you know` element of auth.

**Comment by adrw** [comment] 2022-08-05 12:41
Thanks for the context @james-d-elliott!

**Comment by james-d-elliott** [comment] 2022-09-13 23:02
See here for passwordless auth: https://github.com/authelia/authelia/issues/2827

**Comment by james-d-elliott** [comment] 2022-09-14 00:53
Yeah no clue what you mean.

**Comment by james-d-elliott** [comment] 2022-09-14 02:20
> The passkey are for objective to kill the password.

What their intention is irrelevant. They are exactly the same as WebAuthn. They will *NOT* be treated as special. They will be treated as exactly the same as any other WebAuthn option. I have already answered this. What you're describing is #2827, passwordless authentication which has absolutely nothing to do with passkeys. 

They will be supported as a 2FA option until #2827 is implemented.

> So does authelia (if they add passkey support) will they let us (like now) have the choice to set (passkey + 2FA) on certain domain ?

If we support passkeys they will be supported the same as any other 2FA option. If you set `two_factor` you will enter your username and password, have the option to sign in via TOTP, WebAuthn, or  Duo. If you choose WebAuthn and have a passkey configured then you'll be able to use that.

**Comment by james-d-elliott** [comment] 2022-11-29 03:54
Closed as this is 100% confirmed as a duplicate of #2761, Passkeys are not special other than the fact the Webauthn RP must specify if it wants a device-locked credential. We will also unlikely implement #2761 until such a time as we can control the device-locked behavior as passkeys have a fundamental different security headache that other webauthn credentials do not have.

It's also important to note that Apple is not special at all in this instance Microsoft and Android both support the technology known as Passkeys, and it is a [FIDO Alliance technology](https://fidoalliance.org/passkeys/).

**Closed by james-d-elliott** 2022-11-29 03:54 UTC
Labels: type/feature, area/webauthn, type/duplicate
