### ISSUE TITLE
Authelia docker container fails to run when SMTP password provided.

### ISSUE THREAD

**Issue by cskwrd** [authelia/authelia#2311] opened 2021-08-23 02:34 UTC
### Description

Authelia docker container fails to run when SMTP vault secret provided but filesystem notifier configured.

### Expected Behaviour

Filesystem notifier is configured without errors.

### Reproduction Steps

1. Remove reference to SMTP notifier in configuration YAML file.
2. Configure filesystem notifier in configuration YAML file.
3. Configure SMTP vault secret.
4. Run container.
5. See errors (about multiple notifier configs) in container logs.

**Comment by nightah** [comment] 2021-08-23 02:39
This is not a bug and working as intended.

You should only have one notifier configured at any given time (filesystem or smtp).
Configuring both this will result in an error in Authelia by design.

https://www.smarthomebeginner.com/docker-authelia-tutorial/ and https://github.com/htpcBeginner/docker-traefik/blob/master/docker-compose-t2.yml seems to be the #1 culprit of suggesting users configuring both, this is incorrect.

**Comment by nightah** [comment] 2021-09-22 23:56
Closed as this behaviour is expected. If you need assistance please let us know and we can reopen this issue.

**Closed by nightah** 2021-09-22 23:56 UTC
Labels: Question
