### ISSUE TITLE
Allow multiple 2FA tokens/methods.

### ISSUE THREAD

**Issue by jtagcat** [authelia/authelia#1559] opened 2020-12-23 17:48 UTC
It's not unusual for people to have a secondary, backup token.

The current behaviour is confusing, and just overwrites the previously registered token.

**Comment by jtagcat** [comment] 2020-12-23 17:50
Bug from downstream: https://git.k-space.ee/k-space/overnode-cluster/issues/30

**Comment by nightah** [comment] 2020-12-23 21:42
Duplicate of #275.

**Closed by nightah** 2020-12-23 21:42 UTC
