### ISSUE TITLE
Switch from inline style to normal file

### ISSUE THREAD

**Issue by BirdInFire** [authelia/authelia#3286] opened 2022-05-02 17:35 UTC
### Description

Actually move all inline code to proper file because for now maintaining the "best practice" CSPv3 mean something like that : my csp to work and have the "best practice" result with nginx.

`add_header Content-Security-Policy "default-src 'none'; script-src 'self'; style-src 'self' 'sha256-jVTsI5S8UNRJvmJ/nqFZmgqBoTXeWiqa4FQ4g9kEvAg=' 'sha256-PpoL88sugL+MixGj6eFNM05Q0l/B2tpC9guyJrsQkSY=' 'sha256-053a5882Bziw9xJoBqiiXkScutNwi7NFo0gfSgn06Jk=' 'sha256-JLTR+13CYf1AEvn6+XWlQDtGeLUWmuH1kkyyfgDzf1U=' 'sha256-aXvVHjR/C2zncGrKbZI9A2aQJWqGLt6FSP+vF1kjv1g=' 'sha256-86xT7xtprIrMk0BWEWnnmoInevAHd5oW2X9eTbU0MnQ=' 'sha256-6y7WJjf5UmqTyodR6qZk7zX4EDmiF+mg2XwcPgt7NsQ=' 'sha256-+Lap7joSjKZRlY1cqyXBnMsxDWne5NSO9YcZfdh+QX8=' 'sha256-DBmloQR65eJ1Jpjwj4nMz+fyemR18opBQgzsGSwmgv4=' 'sha256-D+G4S5G0lhy0h0D/aC0s/MsNveaf5u703eMYo+eXCxE=' 'sha256-47DEQpj8HBSa+/TImW+5JCeuQeRkm5NMpJWZG3hSuFU=' 'sha256-AbpHGcgLb+kRsJGnwFEktk7uzpZOCcBY74+YBdrKVGs=' 'sha256-SaBZi50YC1JovbwD2xC+etoxfEzi74QFNIk0zHH8MXE=' 'sha256-LWtc3mCrQTe9veiwT2jY+Lg2kfIxbYtk5etXkKd9CCs=' 'sha256-Arr8PLNstSXxH0AnTNUHamt+sB/F1xmKootnJE4+jkY=' 'sha256-jVe9ylmXQBRxPeRbWXFSDyrjRb/+FDQHdTP8pbngfzo='; img-src 'self'; connect-src 'self'; manifest-src 'self'; upgrade-insecure-requests; block-all-mixed-content;" always;`

And maintain these SHA256 is a pain in the *****, the alternative is allowing 'unsafe-inline' but it will cause the loosing of the "best practice" result.

### Use Case

Maintain Proper CSP for more big server, because the CSP i have generated here is unmaintainable for big structure, and they will simply add 'unsafe-inline' witch is not a best practice.

**Comment by james-d-elliott** [comment] 2022-05-02 21:10
Please provide citations that have some form of authority behind them. In addition can you explain what is lacking with the CSP functionality we provide? Why are you using nginx instead of allowing Authelia to write the CSP header?

**Comment by BirdInFire** [comment] 2022-05-02 21:19
> Please provide citations that have some form of authority behind them. In addition can you explain what is lacking with the CSP functionality we provide? Why are you using nginx instead of allowing Authelia to write the CSP header?

in the case of authelia is behind any sort of reverse proxy, will retake the exemple of nginx, i use it to centralize and load balance my connection, so authelia cannot write it himself since the instance of authelia can change (and the source of the database to) all provided by the reverse proxy.

For my "code block" it's the CSP i HAD to do to actually make authelia work behind nginx with CSP, and have a good practice , can be scored on some tester like https://securityheaders.com or https://www.immuniweb.com/websec/ (this one can generate false negative (so say it's not compillant when it's compillant), but score mean nothing, 'unsafe-inline' aren't named "unsafe" for nothing...

And even if Authelia write the csp himself ... it does not solve the fact the file are inline, witch are not the best (warning (you can see one if you scan securityheader with himself) : https://securityheaders.com/?q=securityheaders.io&followRedirects=on (to lazy to redo the same with immuniweb.

**Comment by james-d-elliott** [comment] 2022-05-02 23:16
> in the case of authelia is behind any sort of reverse proxy, will retake the exemple of nginx, i use it to centralize and load balance my connection, so authelia cannot write it himself since the instance of authelia can change (and the source of the database to) all provided by the reverse proxy.

As far as I'm aware this is not valid. The CSP nonce is used for content that's part of the SPA, which means once the page is loaded the subsequent page loads do not matter, and will be trusted since they are all part of the same domain. I have never seen CSP errors as a result of our nonce and high availability setup. Are you actually sure this occurs WITHOUT setting the CSP via nginx, or is  it WITH headers, or are you speculating?

> For my "code block" it's the CSP i HAD to do to actually make authelia work behind nginx with CSP, and have a good practice , can be scored on some tester like https://securityheaders.com or https://www.immuniweb.com/websec/ (this one can generate false negative (so say it's not compillant when it's compillant), but score mean nothing, 'unsafe-inline' aren't named "unsafe" for nothing...

We _**DO NOT**_ use unsafe-inline. Both sites claim the CSP has no issues with our base CSP. Sounds more like the CSP you implemented with nginx is having issues according to those sites. With zero evidence to your claims that it's a best practice and the considerable work required initially and the increased maintenance burden I don't believe this represents a good choice for Authelia.

**Comment by BirdInFire** [comment] 2022-05-02 23:30
> As far as I'm aware this is not valid. The CSP nonce is used for content that's part of the SPA, which means once the page is loaded the subsequent page loads do not matter, and will be trusted since they are all part of the same domain. I have never seen CSP errors as a result of our nonce and high availability setup. Are you actually sure this occurs WITHOUT setting the CSP via nginx, or is it WITH headers, or are you speculating? I personally use a HA setup and do not have this issue.

Actually my setup prevent any header to pass from the software to the proxy, so the proxy will always override the software like i said early SOME (not you) software have mis-configured their settings so override is the only way to correct it.
> 
> We _**DO NOT**_ use unsafe-inline. Both sites claim the CSP has no issues with our base CSP. Sounds more like the CSP you implemented with nginx is having issues according to those sites. With zero evidence to your claims that it's a best practice and the considerable work required initially and the increased maintenance burden I don't believe this represents a good choice for Authelia.

Never said you used it, i ask if possible (later during the dev or when the dev have some time or rewrite these file (for any reason) make them to separate file).
Like that even for authelia who have to maintain proper csp it's easiers.

And simply use the CSP provided do not fit my theat model (whitch include the protection again supply chain attack (if authelia is infected by an external lib or a rogue contributor), my SCP will generate a report and i will see it nearly instantly).

I have NEVER asked it like for the next update, i think move from inline to file, is better for the dev less csp maintenance (for those like me who prefer avoid no-once as much as we can.

Now it's only an improvement, so feel free (the dev) to say no.

**Comment by james-d-elliott** [comment] 2022-05-03 11:58
> I have NEVER asked it like for the next update, i think move from inline to file, is better for the dev less csp maintenance (for those like me who prefer avoid no-once as much as we can.

It's not really about when you're asking for it at all.

1. The proposed changes _very likely_ represent a more cumbersome and time consuming dev worklfow.
2. You say you want to avoid `nonce` but have yet to provide a compelling reason as to why you'd avoid `nonce`.
3. You have made claims that it's a best practice but when asked to provide citations of this provided sites that not only do not support this position but also disagree with it.
4. You have made claims that it "doesn't work" in highly available deployments but this can't be replicated and when asked specifically about it you don't answer.

Overall you're coming over as demanding and not very forthcoming or helpful with regards to providing information.

> Like that even for authelia who have to maintain proper csp it's easiers.

I highly doubt this. It's possible we've missed something but my recollection is we require it with or without inline styles and changing that requirement represents a significant workflow change that is significantly more cumbersome (i.e. slow) to use, this may have changed but I don't think so.

> And simply use the CSP provided do not fit my theat model (whitch include the protection again supply chain attack (if authelia is infected by an external lib or a rogue contributor), my SCP will generate a report and i will see it nearly instantly).

This seems like a misguided assumption. Every time Authelia updates this will change the hash of a majority of inline scripts. If you don't update before verifying the changes then it will not be an issue. If you update before verifying CSP will fail, or if you update and automatically update your hashes it is exactly as same as using the nonce (you're trusting whatever is bundled at that moment in time, rogue or not). The `nonce` is cryptographically unique to every load of the SPA/PWA. Though maybe I misunderstand what you mean, can you elaborate?

**Comment by BirdInFire** [comment] 2022-05-06 18:28
> > I have NEVER asked it like for the next update, i think move from inline to file, is better for the dev less csp maintenance (for those like me who prefer avoid no-once as much as we can.
> 
> It's not really about when you're asking for it at all.
> 
> 1. The proposed changes _very likely_ represent a more cumbersome and time consuming dev worklfow.
> 2. You say you want to avoid `nonce` but have yet to provide a compelling reason as to why you'd avoid `nonce`.
> 3. You have made claims that it's a best practice but when asked to provide citations of this provided sites that not only do not support this position but also disagree with it.
> 4. You have made claims that it "doesn't work" in highly available deployments but this can't be replicated and when asked specifically about it you don't answer.
> 
> Overall you're coming over as demanding and not very forthcoming or helpful with regards to providing information.
> 
> > Like that even for authelia who have to maintain proper csp it's easiers.
> 
> I highly doubt this. It's possible we've missed something but my recollection is we require it with or without inline styles and changing that requirement represents a significant workflow change that is significantly more cumbersome (i.e. slow) to use, this may have changed but I don't think so.
> 
> > And simply use the CSP provided do not fit my theat model (whitch include the protection again supply chain attack (if authelia is infected by an external lib or a rogue contributor), my SCP will generate a report and i will see it nearly instantly).
> 
> This seems like a misguided assumption. Every time Authelia updates this will change the hash of a majority of inline scripts. If you don't update before verifying the changes then it will not be an issue. If you update before verifying CSP will fail, or if you update and automatically update your hashes it is exactly as same as using the nonce (you're trusting whatever is bundled at that moment in time, rogue or not). The `nonce` is cryptographically unique to every load of the SPA/PWA. Though maybe I misunderstand what you mean, can you elaborate?

I actually do use watchtower for automatic update, so i would love a simple warning in the changelog of the update if a file in the CSP change (because if we are warned when an update is delivered on git, we can add this "new" hash into our csp even before it reach the docker auto update (than aften when the page break).

**Comment by james-d-elliott** [comment] 2022-05-09 01:46
All of the web resource files are published in GitHub releases which can be utilized to automate something like this. For example for 4.35.2: https://github.com/authelia/authelia/releases/download/v4.35.2/authelia-v4.35.2-public_html.tar.gz

I'm closing this as I don't see the benefit in implementing this and when asked for information to try and clarify it has just been ignored mostly. The CSP spec was designed in such a way that it can be implemented effectively without using the practice of a single stylesheet used by web 1.0 sites in the 1990's.

**Closed by james-d-elliott** 2022-05-09 01:46 UTC
Labels: Feature Request
