### ISSUE TITLE
Suggestion: Password policy via regexps

### ISSUE THREAD

**Issue by KoltesDigital** [authelia/authelia#1631] opened 2021-01-24 20:23 UTC
When defining a new password, Authelia could enforce some rules. IMHO this has become very common nowadays (whether it's a good thing or not is another debate: I personally believe in password managers). Policies I've commonly seen state: must be at least N character long, include at least one uppercase letter, one lowercase letter, one digit, one special char. While each of these items could have a corresponding configuration field, I prefer a more flexible way, at the expense of CPU power: define them with regexps. I suggest to add a new configuration section `password_policy` and an inner field `regexps`. So the new password is validated iff it passes all regexps.

Because each of these rules should only be specified once, and has a corresponding error message if validation fails, I suggest that this configuration field should be a `map[string]string`. Alternatively it could be a list of `struct { regexp string message string }`. For i18n, perhaps multiple strings could be given...

On the browser side, there could be a pre-validation, which could be an extra benefit for the user experience. JS regexps and Go regexps could differ, so in case it does, a configuration field `password_policy.js_regexps` could define the regexps to be used on the client side. (I'm not aware of a tool which translates one to the other). Considering the `js_regexps` field if it's defined, or considering `regexps` if not, the JS would try to load the regexps: if the parser raises an error, that regexp is simply not taken into account. The correct regexp are then used to validate the password. If there's only one JS regexp, [HTML5 password input's validation attribute could be used](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/password#validation) for a better integration with the browser (e.g. would work even if JS is disabled). If no JS regexps are defined, no pre-validation occurs, but of course the server still validates the new password.

FTR, some examples:

```yaml
password_policy:
  regexps:
    "^.{16,}?$": must be at least 16 character long
    "[A-Z]": must have at least one uppercase letter
    "[a-z]": must have at least one lowercase letter
    "[0-9]": must have at least a digit
    "[!\"#$%&'()*+,\\-./:;<=>?@[\\\\\\]^_`{|}~]": must have at least a special character
  # No js_regexps field because all these Go regexps are also JS compliant.
```

Any opinion?

**Comment by nightah** [comment] 2021-01-31 01:26
I see that as a duplicate of #361.

Having said that I'd say we haven't particularly prioritised said issue because this can be implemented/enforced with LDAP quite easily.

If/when implemented my suggestion would be to make the syntax for configuration simpler than regexes (while the implementation may actually still utilise regexes under the hood).

Essentially a lot of Authelia's userbase may not really know how to read/interpret and implement regexes we should give some simple language and syntax that allows them to configure and implement this.

Thoughts @james-d-elliott @clems4ever?

Not sure if we want to keep this open or move your commentary @KoltesDigital into the aforementioned issue, I'll await what the team thinks.

**Comment by KoltesDigital** [comment] 2021-01-31 06:52
Surprisingly I didn't find #361, I admit this is similar in the needs. Also I didn't know about ppolicy, which is nice to have in any case, but I feel like the gateway used to change the password (Authelia) could more easily provide feedback, hence the map or array with messages (it looks like OpenLDAP can only state `Authentication token manipulation error`).

**Comment by nightah** [comment] 2021-01-31 08:55
@KoltesDigital depending on the LDAP implementation it's actually possible to get quite granular details regarding the type of complexity error.

At some point I'm going to expand our OpenLDAP and ActiveDirectory (Samba AD) suites to get a better mapping of the error messages so we can provide much more concise errors to the user when attempting to reset their password in the frontend.

**Comment by mind-ar** [comment] 2021-12-10 23:28
hello, I would like to add some notes about this functionality:
* maybe is a good idea to add some validation in the front-end, like is suggested in https://cheatsheetseries.owasp.org/cheatsheets/Authentication_Cheat_Sheet.html: "Include password strength meter to help users create a more complex password"
* backend validation may be a "must be" feature when  #1538 is implemented, cause not ldap to validate password strength

**Comment by mind-ar** [comment] 2021-12-11 19:03
Hi, i have some spare time to take this issue, if it's worth it.
I have some doubts about how to face it:

### 1 - password rules vs entropy
1. password strength determined by password rules:
```
password_policy:
  numbers: true
  uppercase: true
  lowercase: true
  specials: true
  min_length: 8
```
in this case the password must comply with all the defined rules

2.  password strength determined by entropy
```
password_policy:
  min_strength: weak
  acceptable_entropy: 50
  strong_entropy: 80
```
In this case, the password is marked as "weak", "acceptable" or "strong" (or something like that)


### 2 - frontend vs backend
1. frontend
* the rules are fetched once
* all logic resides in react

2. backend
* each user's input is sent to the backend
* all logic resides in go
* some advantages:
  * the backend have the logic to revalidate before save
  * can add some extra checks (blacklists, haveibeenpwned api, etc)

**Comment by nightah** [comment] 2021-12-11 23:22
I'm personally in favour of an entropy-based approach but I think that could potentially be confusing for some users therefore password rules might actually make the most sense.

In terms of the validation, I think there needs to be a mixture of both frontend and backend and we need to be cognizant of the fact that some users could actually be using LDAP which may have its own password policy that needs to be adhered to.

So under those types of scenarios, the frontend validation is useful for both File and LDAP based backends mainly to provide visual indicators/strength bars etc which can prompt a user during the password reset and I would probably suggest a library like zxcvbn.
In the case of LDAP the frontend password rules can just be used to marry up against the LDAP ppolicy.

Regarding backend validation, users finalized input already is sent across in the POST to `/api/reset-password` handler: https://github.com/authelia/authelia/blob/e5d8c1f84959b841a2a550a1a09b6be10e7be38b/internal/handlers/handler_reset_password_step2.go#L22-L44 and this is where I would really look to perform any additional logic and validation (any of the extra checks) before finally resetting the password.

When I looked at this in the past for haveibeenpwned there was no mechanism to set a community API key for Authelia so each respective instance/administrator would need to pay for and activate their own API key.

If you have any other questions or want to discuss further please don't hesitate to reach out either on Matrix or Discord.

**Comment by mind-ar** [comment] 2021-12-15 02:43
I think i can implement this in frontend
- three modes (active mode will be fetched from the api when the page is load)
  - none: no password policy
  - entropy: password strength will be calculated using zxcvbn (800KB uncompressed)
  - rules: password strength will be calculated according with the rules in config file (i.e. requireUppercase, requireLowerCase, etc)

here's some examples (using zxcvbn and raw divs)

![2021-12-14T23:22:49,885638058-03:00](https://user-images.githubusercontent.com/10672208/146111887-bab1771e-5a3e-42d1-9fd7-e3070a49ddfc.png)

![2021-12-14T23:23:01,295288440-03:00](https://user-images.githubusercontent.com/10672208/146111893-2b81cf8c-377b-4659-901c-3ada7130eb70.png)

![2021-12-14T23:28:32,667450380-03:00](https://user-images.githubusercontent.com/10672208/146111898-5d3a76da-7736-48bf-931b-b13b02e1de95.png)

![2021-12-14T23:23:24,742598210-03:00](https://user-images.githubusercontent.com/10672208/146111895-7a36fe65-14db-425d-882d-7a91e5c323f8.png)

![2021-12-14T23:23:43,510637352-03:00](https://user-images.githubusercontent.com/10672208/146111896-7d671915-843d-4a4c-884c-20b35834d7c4.png)

any suggestion or correction is welcome

**Comment by nightah** [comment] 2021-12-15 03:30
SGTM, only suggestion I have with the above is that the darker green and light green colours be swapped for the strength indicator.

Or perhaps we use Red -> Dark Orange -> Light Orange -> Yellow -> Light Green.

**Comment by mind-ar** [comment] 2021-12-15 18:05
which pallete?

![imagen](https://user-images.githubusercontent.com/10672208/146240084-9dafb9ba-86c2-4aa6-8142-14a053d3f992.png)

**Comment by james-d-elliott** [comment] 2022-04-03 00:48
Implemented effectively above just in a different way.

**Closed by james-d-elliott** 2022-04-03 00:48 UTC

**Comment by KoltesDigital** [comment] 2022-04-17 15:16
Great, thanks a lot!
