### ISSUE TITLE
Support of multiple authentication methods on GUI

### ISSUE THREAD

**Issue by idavollen** [authelia/authelia#7768] opened 2024-08-28 07:58 UTC
### Description

We can use the username/password with 2FA against LLDAP as the default authentication method. If a new user tries to access our web app protected by Authelia, she can not log in at all. It'll be really great if the Authelia GUI could also list some alternative configured authentication methods, such as Login with Github, Login with Google, Login with Linkedin, etc via OpenID Connect. Authelia could either seamlessly let these social media account login after successfully receiving the ID_Token or use the _profile_ scope to retrieve user details from these social media OIDC Providers to help sign-up process on Autheliat GUI. These alternative social media authentication methods with OIDC could improve both user experiences and our onboarding process for new customers.

### Use Case

We can use the username/password with 2FA against LLDAP as the default authentication method. If a new user tries to access our web app protected by Authelia, she can not log in at all. It'll be really great if the Authelia GUI could also list some alternative configured authentication methods, such as Login with Github, Login with Google, Login with Linkedin, etc via OpenID Connect.

### Pre-Submission Checklist

- [X] I agree to follow the [Code of Conduct](http://www.authelia.com/code-of-conduct)

- [X] I have checked for related issues and checked the documentation

**Comment by james-d-elliott** [comment] 2024-08-28 08:26
Duplicate of #2728

**Closed by james-d-elliott** 2024-08-28 08:26 UTC
Labels: priority/4/normal, type/feature, status/needs-design

**Comment by idavollen** [comment] 2024-08-28 09:28
In fact, it's not a duplicate for the mentioned one concerns support of OIDC, but mine conserns support of multiple authetication methods, OIDC is just a sort of them of interest.

**Comment by james-d-elliott** [comment] 2024-08-28 22:53
If your idea is not to allow users to sign in via OpenID Connect 1.0 providers or via username and password what is your idea exactly?

**Comment by idavollen** [comment] 2024-08-29 21:02
That is not what my idea concerns about. The new feature I desire with Authelia is to support multiple authentication methods on the Authelia login GUI as following:
![Screenshot 2024-08-29 at 23 00 10](https://github.com/user-attachments/assets/02e823d5-90cf-4863-b224-beb506fe5735)

**Comment by james-d-elliott** [comment] 2024-08-29 22:39
Yep that's exactly what that other FR is.

**Comment by idavollen** [comment] 2024-08-30 05:42
I see your point, the Relying Party, RP is the terminology used in OIDC, the Client is the one used in OAuth 2 :)
