### ISSUE TITLE
Mobile OTP device registration HTML image boken

### ISSUE THREAD

**Issue by akusei** [authelia/authelia#1143] opened 2020-06-21 18:51 UTC
When clicking on the link in a registration email it takes you to the `https://domain.tld/one-time-password/register?token=longtoken` URL which contains 2 links, one for a google app and one for an iphone app. Both of these images are broken. I'm using authelia version 4.20

It looks like a template somewhere is not being populated with the Base variable. The link to these images looks like this:

```html
<img src="{{.Base}}/static/media/googleplay-badge.56b44686.svg" alt="google play" style="width: 128px;">

<img src="{{.Base}}/static/media/applestore-badge.d0558d91.svg" alt="apple store" style="width: 128px;">
```
This looks like it's a graphical bug with templates but I could definitely be doing something wrong in my configuration but I didn't see any way to change Base or PUBLIC_URL from the react environment.

**Comment by clems4ever** [comment] 2020-06-21 21:07
Hello @akusei , thank you for reporting this issue. I can reproduce it locally. For the record, I reproduce in CI mode but not in dev mode.

I'll let you know once I have a solution.

**Comment by akusei** [comment] 2020-06-22 02:34
I'm not sure if this is related in any way but when you navigate to the QR code from the email link on a mobile device, it blurs out the QR code, puts and X on it and says the device can't be registered

**Comment by clems4ever** [comment] 2020-06-22 06:42
This blurred QR code appears if you refresh the page, it's because the token in the URL is a one-time token. Once the device is registered, we prevent anyone to put hands on the secret too. If it happens to users, they should restart the enrollment process.

Maybe we can be a little clearer on this in the error messages.

**Comment by akusei** [comment] 2020-06-22 19:03
That makes sense and is definitely what you should be doing but this is causing mobile users (android in particular) to now be able to easily register their device. It only seems to happen when you click the link in an email which takes you to a gmail app internal browser window. This window must refresh automatically or something because it immediately goes blurred with the red X.

Perhaps there could be a check for a user accessing on mobile, if so then allow a very quick refresh window?

**Comment by clems4ever** [comment] 2020-06-22 21:11
Ok so I suggest you file another issue for that specific problem @akusei . I'll try to reproduce ASAP.

Regarding the initial problem of broken link, we have found what it is due to with @nightah (https://github.com/authelia/authelia/pull/1027) but the fix is not trivial or at least not trivial for addressing the root cause, we are looking for the best approach to solve it and we'll keep you posted.

**Comment by akusei** [comment] 2020-06-22 21:18
Understood, I'll do a little more testing on my end for the blurred image issue before I open a new ticket since it might be just me and if it isn't, it needs to be its own issue

**Comment by nightah** [comment] 2020-06-23 08:29
Thanks for reporting this issue @akusei.
We have managed to understand the root cause and created the fix, expect it to be merged in the not too distant future!

**Closed** 2020-06-23 23:37 UTC
Labels: Bug, In Progress, P1
