### ISSUE TITLE
Add primary keys to SQL tables for percona/galera support

### ISSUE THREAD

**Issue by Ornias1993** [authelia/authelia#1337] opened 2020-09-23 00:44 UTC
Percona is quite strict on having primary keys on all tables (and rightly so).
Please add primary keys to all tables, even if it's just an auto-increment.

It's mostly just the following tables:
_authentication_logs_ (could just get a auto-increment primary key added)
_identity_verification_tokens_ (could just set the token as primary key)

**Comment by james-d-elliott** [comment] 2020-10-23 01:11
This is definitely something we can do. We have a plan to make some changes to the DB schema shortly so I will try to squeeze that in then.

**Comment by Ornias1993** [comment] 2020-10-23 09:42
@james-d-elliott Awesome.
I did some initial tests by manually adding those colums and it worked out just fine btw :)

**Comment by james-d-elliott** [comment] 2020-10-23 10:15
Yeah making them primary should be fine, it's just making sure everyone is on the same schema state when we do it. That way there is no desync.

**Comment by Ornias1993** [comment] 2020-10-23 10:32
Yeah the migration is the most work indeed 👍 
Thanks for picking it up! :)

**Comment by 76090** [comment] 2021-03-23 13:45
James the SQL was believable. Thank you!

**Comment by james-d-elliott** [comment] 2021-10-09 22:35
It has definitely been pushed a bit, it is also a major holdup for future features so it's something I'm actively working on. https://github.com/authelia/authelia/pull/2431

**Comment by pdf** [comment] 2021-10-10 14:08
FWIW, my preference would be to cut a release with the updated base table structure, so that the app can at least be deployed on a cluster with default configuration, and push feature updates afterwards with additional migrations as/when needed.

**Comment by james-d-elliott** [comment] 2021-10-10 21:40
The issue is we have two tables which require upgrades that are not possible via migrations. I want both of these changes to occur in one step in order to prevent a horrible migration process. This way I can realistically create a simple method to migrate down as well (either now or later, more likely to be now).

**Comment by pdf** [comment] 2021-10-10 22:00
I'd suggest all the existing tables should probably be modified to add an int primary key. Getting the structure right this pass is a sound idea.

What prompted my repliy is only that your earlier comment made it sound like release of these schema changes would be predicated on some future feature work, and the current schema is a blocker for deployment in some environments.

All changes should be possible via migration though (depending I guess on your definition of migration), can you expand on what problems you're facing in updating the schema?

**Comment by james-d-elliott** [comment] 2021-10-10 22:26
> I'd suggest all the existing tables should probably be modified to add an int primary key. Getting the structure right this pass is a sound idea.

I'm actually a DBA by profession, this was always the plan. It's relatively easy to do this part.

> What prompted my repliy is only that your earlier comment made it sound like release of these schema changes would be predicated on some future feature work, and the current schema is a blocker for deployment in some environments.

A majority of the changes that will be bundled are small. However we'd rather take our time and ensure the process is going to be smooth and non-disruptive. We could definitely do it the way you're suggesting, and I know this has been pushed a few times already. However the key thing that this is needed for is OIDC storage, which is the #1 thing on our priority list, it's very unlikely that that change will be bundled with this one. This will be released (as v1) prior to the OIDC change to be later released (as v2). 

> All changes should be possible via migration though (depending I guess on your definition of migration), can you expand on what problems you're facing in updating the schema?

I would argue a migration is something that can be purely done via SQL syntax. The problem only exists when you have to do data transformation that can't be done in one of our SQL providers. Encrypting stored data, and modifying a byte array stored as a base64 TEXT type to a byte array native type (BLOB/BYTEA). Both are not possible on SQLite. For MySQL/PostgreSQL/SQLite we also have to ensure the encryption method is consistent, so realistically that's something that has to be done with software.

**Comment by james-d-elliott** [comment] 2021-10-10 22:29
Here's a peek at the schema, considering your interest in scaling databases I'd guess you're using postgres:

```sql
CREATE TABLE IF NOT EXISTS authentication_logs (
    id SERIAL PRIMARY KEY,
    time INTEGER NOT NULL,
    username VARCHAR(100) NOT NULL,
    successful BOOLEAN NOT NULL
);

CREATE TABLE IF NOT EXISTS identity_verification_tokens (
    id SERIAL PRIMARY KEY,
    token VARCHAR(512) NOT NULL
);

CREATE TABLE IF NOT EXISTS migrations (
    id SERIAL PRIMARY KEY,
    time INTEGER NOT NULL,
    schema INTEGER NOT NULL,
    prior INTEGER NULL DEFAULT NULL,
    version VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS totp_configurations (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE,
    algorithm VARCHAR(6) NOT NULL DEFAULT 'sha1',
    digits INTEGER NOT NULL DEFAULT 6,
    totp_period INTEGER NOT NULL DEFAULT 30,
    secret VARCHAR(64) NOT NULL
);

CREATE TABLE IF NOT EXISTS u2f_devices (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE,
    key_handle bytea NOT NULL,
    public_key bytea NOT NULL
);

CREATE TABLE IF NOT EXISTS user_preferences (
    id SERIAL PRIMARY KEY,
    username VARCHAR(100) UNIQUE,
    second_factor_method VARCHAR(11) NOT NULL
);

```

**Closed** 2021-11-23 09:45 UTC
Labels: P3, Feature Request, Good First Issue

**Comment by james-d-elliott** [comment] 2021-11-23 10:24
The change has been merged however it's not ready for use in production. Please wait until the following PR's are merged before using it:

#2588
#2589 
#2137
